apiVersion: v1
kind: ConfigMap
metadata:
  name: "obsenv-ui"
  labels:
    {{- include "obsenv-ui.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.global.baseUrl | quote }}
  OBSENV_API: "obsenv-api/obsenv-api"
  AUTH_GROUP: "lsst-ts-integration-testing-team"
