apiVersion: v1
kind: ConfigMap
metadata:
  name: "obsenv-ui"
  labels:
    {{- include "obsenv-ui.labels" . | nindent 4 }}
data:
  BASE_URL: {{ .Values.global.baseUrl | quote }}
  OBSENV_API: "http://obsenv-api:8080/obsenv-api"
  NEXT_PUBLIC_AUTH_GROUP: "lsst-ts-integration-testing-team"
