db:
  user: "exposurelog"
  passwordkey: "exposurelog-password"
  host: "postgresdb01.tu.lsst.org"
  database: "exposurelog"
lfa:
  s3EndpointUrl: "https://s3.tu.lsst.org"
hinfo:
  latiss:
    enable: true
    tag: "main"
    logConfig: "consdb.hinfo=DEBUG"
  lsstcomcam:
    enable: true
    tag: "main"
    logConfig: "consdb.hinfo=DEBUG"
  lsstcam:
    enable: false
    tag: "main"
pq:
  image:
    tag: "main"
