argo-workflows:
  crds:
    keep: false
  server:
    extraArgs:
    - "--auth-mode=server"
    ingress:
      enabled: True
      ingressClassName: nginx

# The following will be set by parameters injected by Argo CD and should
# not be set in the individual environment values files.
global:
  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
