argo-workflows:
  server:
    ingress:
      hosts:
      - data-dev-workflows.lsst.cloud
    serviceAccount:
      annotations:
        workflows.argoproj.io/rbac-rule: "true"
  sso:
    scopes:
    - email
