server:
  debug: true
ingress:
  hostname:
    readonly: "git-lfs-dev.lsst.cloud"
    readwrite: "git-lfs-dev-rw.lsst.cloud"
config:
  storageProjectName: "data-curation-prod-fbdb"
  bucketName: "rubin-us-central1-git-lfs-dev"
  serviceAccountReadonly: "git_lfs_rw@roundtable-dev-abe2.iam.gserviceaccount.com"
  serviceAccountReadwrite: "git_lfs_rw@roundtable-dev-abe2.iam.gserviceaccount.com"
