# Default values for giftless.

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: ""

# -- Resource limits and requests for the giftless frontend pod
resources: {}

# -- Annotations for the giftless frontend pod
podAnnotations: {}

# -- Node selector rules for the giftless frontend pod
nodeSelector: {}

# -- Tolerations for the giftless frontend pod
tolerations: []

# -- Affinity rules for the giftless frontend pod
affinity: {}

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
image:
  # -- Giftless image to use
  repository: docker.io/datopian/giftless
  # -- Pull policy for the giftless image
  pullPolicy: "IfNotPresent"
  # -- Tag of giftless image to use
  # @default -- The appVersion of the chart
  tag: ""

ingress:
  # -- FQDNs of giftless ingresses
  # @default -- Must be overridden in environment-specific values file
  hostname:
    # -- FQDN for the read-only giftless ingress
    # @default -- Must be overridden in environment-specific values file
    readonly: ""
    # -- FQDN for the read-write giftless ingress
    # @default -- Must be overridden in environment-specific values file
    readwrite: ""
  # -- Additional annotations to add to the ingress
  annotations: {}

server:
  # -- Turn on debugging mode
  debug: false
  # -- Number of processes for server
  processes: 2
  # -- Number of threads per process
  threads: 2

# -- Configuration for giftless server
# @default -- YAML will be used as-is.  cf https://giftless.datopian.com/en/latest/configuration.html
config:
  readonly:
    AUTH_PROVIDERS:
      - "giftless.auth.allow_anon:read_only"
    TRANSFER_ADAPTERS:
      basic:
        factory: "giftless.transfer.basic_external:factory"
        # @default -- Must be overridden in environment-specific values file
  readwrite:
    AUTH_PROVIDERS:
      - "giftless.auth.allow_anon:read_write"  # Ingress does control.
    TRANSFER_ADAPTERS:
      basic:
        factory: "giftless.transfer.basic_external:factory"
        # @default -- Must be overridden in environment-specific values file

global:
  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
