apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: "jira-data-proxy"
  labels:
    {{- include "jira-data-proxy.labels" . | nindent 4 }}
spec:
  path: "{{ .Values.global.vaultSecretsPathPrefix }}/jira-data-proxy"
  type: Opaque
