rubintv:
  siteTag: "summit"

  imagePullSecrets:
  - name: pull-secret

  frontend:
    debug: true
    env:
    - name: S3_ENDPOINT_URL
      value: &s-s3E "https://s3.rubintv.cp.lsst.org"
    - name: RAPID_ANALYSIS_LOCATION
      value: "SUMMIT"
    image:
      repository: ghcr.io/lsst-ts/rubintv
      tag: deploy
      pullPolicy: Always

  workers:
    replicas: 1
    image:
      repository: ts-dockerhub.lsst.org/rapid-analysis
      tag: c0036
      pullPolicy: Always
    uid: 73006
    gid: 73006
    scriptsLocation: /repos/rubintv_analysis_service/scripts
    script: rubintv_worker.py -a rubintv-dev -p 8080 -c /repos/rubintv_analysis_service/scripts/config-temporal.yaml
    env:
    - name: S3_ENDPOINT_URL
      value: *s-s3E
    - name: DAF_BUTLER_REPOSITORY_INDEX
      value: "s3://rubin-summit-users/data-repos.yaml"
    - name: DAF_BUTLER_REPOSITORY
      value: "/sdf/group/rubin/repo/ir2/butler.yaml"
    # nfsMountpoint:
    # - name: auxtel-gen3-data
    #   containerPath: /repo/LATISS
    #   readOnly: false
    #   server: nfs-auxtel.cp.lsst.org
    #   serverPath: /auxtel/repo/LATISS
    # - name: comcam-gen3-data
    #   containerPath: /repo/LSSTComCam
    #   readOnly: false
    #   server: comcam-archiver.cp.lsst.org
    #   serverPath: /repo/LSSTComCam
    # - name: auxtel-data
    #   containerPath: /readonly/lsstdata/auxtel
    #   readOnly: true
    #   server: nfs-auxtel.cp.lsst.org
    #   serverPath: /auxtel/lsstdata
    # - name: comcam-data
    #   containerPath: /readonly/lsstdata/comcam
    #   readOnly: true
    #   server: comcam-archiver.cp.lsst.org
    #   serverPath: /lsstdata
    # - name: project-shared
    #   containerPath: /project
    #   readOnly: false
    #   server: nfs1.cp.lsst.org
    #   serverPath: /project
    # - name: auxtel-gen3-data-temp
    #   containerPath: /data/lsstdata/base/auxtel
    #   readOnly: true
    #   server: nfs-auxtel.cp.lsst.org
    #   serverPath: /auxtel/lsstdata/base/auxtel
    # - name: comcam-gen3-data-temp
    #   containerPath: /data/lsstdata/base/comcam
    #   readOnly: true
    #   server: comcam-archiver.cp.lsst.org
    #   serverPath: /lsstdata/base/comcam
    # - name: allsky-data
    #   containerPath: /data/allsky
    #   readOnly: true
    #   server: nfs-auxtel.cp.lsst.org
    #   serverPath: /auxtel/allsky
    # - name: scratch-shared
    #   containerPath: /scratch
    #   readOnly: false
    #   server: nfs1.cp.lsst.org
    #   serverPath: /scratch/rubintv
    resources:
      requests:
        cpu: 0.5
        memory: 1G
      limits:
        cpu: 1.0
        memory: 2.5G

global:
  tsVaultSecretsPath: /ts/software
