rubintv:
  siteTag: "summit"

  imagePullSecrets:
  - name: pull-secret

  frontend:
    debug: true
    env:
    - name: S3_ENDPOINT_URL
      value: &s-s3E "https://s3.rubintv.cp.lsst.org"
    - name: RAPID_ANALYSIS_LOCATION
      value: "SUMMIT"
    image:
      repository: ghcr.io/lsst-ts/rubintv
      tag: deploy
      pullPolicy: Always

  workers:
    replicas: 1
    image:
      repository: ts-dockerhub.lsst.org/rapid-analysis
      tag: c0036
      pullPolicy: Always
    uid: 73006
    gid: 73006
    scriptsLocation: /repos/rubintv_analysis_service/scripts
    script: rubintv_worker.py -a rubintv-dev -p 8080 -c /repos/rubintv_analysis_service/scripts/config-temporal.yaml
    env:
    - name: S3_ENDPOINT_URL
      value: *s-s3E
    - name: DAF_BUTLER_REPOSITORY_INDEX
      value: "s3://rubin-summit-users/data-repos.yaml"
    - name: DAF_BUTLER_REPOSITORY
      value: "/sdf/group/rubin/repo/ir2/butler.yaml"
    resources:
      requests:
        cpu: 0.5
        memory: 1G
      limits:
        cpu: 1.0
        memory: 2.5G

global:
  tsVaultSecretsPath: /ts/software
