csc_collector:
  secrets:
  - name: nexus3-docker
    key: pull-secret
    type: kubernetes.io/dockerconfigjson
  - name: ts-salkafka
    key: ts/software/ts-salkafka
  - name: lfa
    key: ts/software/lfa

love-commander:
  image:
    repository: ts-dockerhub.lsst.org/love-commander
    pullPolicy: Always
  env:
    S3_INSTANCE: tuc
  envSecrets:
  - name: AWS_ACCESS_KEY_ID
    secretName: lfa
    secretKey: aws-access-key-id
  - name: AWS_SECRET_ACCESS_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  - name: MYS3_ACCESS_KEY
    secretName: lfa
    secretKey: aws-access-key-id
  - name: MYS3_SECRET_KEY
    secretName: lfa
    secretKey: aws-secret-access-key
  service:
    enabled: true
    port: 5000
    type: ClusterIP

love-manager:
  image:
    repository: ts-dockerhub.lsst.org/love-manager
    pullPolicy: Always
  env:
    SERVER_URL: tucson-teststand.lsst.codes
    OLE_API_HOSTNAME: tucson-teststand.lsst.codes
    AUTH_LDAP_1_SERVER_URI: ldap://ipa1.tu.lsst.org
    AUTH_LDAP_2_SERVER_URI: ldap://ipa2.tu.lsst.org
    AUTH_LDAP_3_SERVER_URI: ldap://ipa3.tu.lsst.org
    DB_HOST: postgresdb01.tu.lsst.org
    REDIS_CONFIG_EXPIRY: 5
    REDIS_CONFIG_CAPACITY: 5000
    LOVE_SITE: tucson
    LOVE_PRODUCER_WEBSOCKET_HOST: love-nginx-service/love/manager/ws/subscription
  envSecrets:
    AUTHLIST_USER_PASS: authlist-user-pass
    AUTH_LDAP_BIND_PASSWORD: auth-ldap-bind-password
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 25
    targetCPUUtilizationPercentage: 75
  resources:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 750m
      memory: 1000Mi
  readinessProbe:
    tcpSocket:
      port: 8000
    initialDelaySeconds: 20
    periodSeconds: 10
  redis:
    image:
      repository: redis
      tag: '7'
      pullPolicy: IfNotPresent
    config: |
      timeout 60
  viewBackup:
    enabled: true
    image:
      repository: ts-dockerhub.lsst.org/love-view-backup
      pullPolicy: Always
    schedule: 0 12 * * *

love-nginx:
  image:
    repository: nginx
    tag: 1.25.1
    pullPolicy: Always
  ingress:
    hostname: tucson-teststand.lsst.codes
    httpPath: /love
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  imagePullSecrets:
  - name: nexus3-docker
  initContainers:
    frontend:
      image:
        repository: ts-dockerhub.lsst.org/love-frontend-k8s
        pullPolicy: Always
    manager:
      image:
        repository: ts-dockerhub.lsst.org/love-manager-static
        pullPolicy: Always
      command:
      - /bin/sh
      - -c
      - mkdir -p /usr/src/love-manager; cp -Rv /usr/src/love/manager/media /usr/src/love-manager; cp -Rv /usr/src/love/manager/static /usr/src/love-manager
  staticStore:
    name: love-nginx-static
    storageClass: rook-ceph-block
    accessMode: ReadWriteOnce
    claimSize: 2Gi
  nginxConfig: |
    server {
      listen 80;
      server_name localhost;
      location /love {
        root   /usr/src/love-frontend;
        try_files $uri$args $uri$args/ $uri/ /love/index.html;
      }
      location /love/manager {
          proxy_pass http://love-manager-service:8000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_redirect off;
      }
      location /love/media {
          alias /usr/src/love-manager/media;
      }
      location /love/manager/static {
          alias /usr/src/love-manager/static;
      }
      location /love/manager/media {
          alias /usr/src/love-manager/media;
      }
      location /love/simcam {
          proxy_pass http://simulation-gencam-service.calsys:5013/;
          proxy_set_header Host $host/love;
      }
    }
  loveConfig: |
    {
      "alarms": {
        "minSeveritySound": "serious",
        "minSeverityNotification": "warning"
      },
      "camFeeds": {
        "simcam": "/love/simcam"
      },
      "efd": {
        "defaultEfdInstance": "tucson_teststand_efd"
      }
    }

love-producer:
  image:
    repository: ts-dockerhub.lsst.org/love-producer
    pullPolicy: Always
  env:
    WEBSOCKET_HOST: love-nginx-service/love/manager/ws/subscription
  producers:
  - name: auxtel
    cscs:
      ataos: ATAOS:0
      atdome: ATDome:0
      atdometrajectory: ATDomeTrajectory:0
      athexapod: ATHexapod:0
      atmcs: ATMCS:0
      atpneumatics: ATPneumatics:0
      atptg: ATPtg:0
  - name: comcam
    cscs:
      cccamera: CCCamera:0
      ccheaderservice: CCHeaderService:0
      ccocps: OCPS:2
      ccoods: CCOODS:0
  - name: eas
    cscs:
      auxteless01: ESS:201
      auxteless02: ESS:202
      auxteless03: ESS:203
      auxteless04: ESS:204
      calibhilless01: ESS:301
      dimm1: DIMM:1
      dimm2: DIMM:2
      dsm1: DSM:1
      dsm2: DSM:2
      m2ess106: ESS:106
      mtdomeess01: ESS:101
      mtdomeess02: ESS:102
      mtdomeess03: ESS:103
      tmaess01: ESS:1
      tmaess104: ESS:104
      tmaess105: ESS:105
      weatherforecast: WeatherForecast:0
  - name: genericcamera
    cscs:
      gcheaderservice1: GCHeaderService:1
      genericcamera1: GenericCamera:1
  - name: latiss
    cscs:
      atcamera: ATCamera:0
      atheaderservice: ATHeaderService:0
      atocps: OCPS:1
      atoods: ATOODS:0
      atspectrograph: ATSpectrograph:0
  - name: mtm1m3
    cscs:
      mtm1m3: MTM1M3:0
  - name: mtm2
    cscs:
      mtm2: MTM2:0
  - name: obssys
    cscs:
      atscheduler: Scheduler:2
      atscriptqueue: ScriptQueue:2
      authorize: Authorize:0
      love: LOVE:0
      mtscheduler: Scheduler:1
      mtscriptqueue: ScriptQueue:1
      watcher: Watcher:0
  - name: simonyitel
    cscs:
      camerahexapod: MTHexapod:1
      m2hexapod: MTHexapod:2
      mtaos: MTAOS:0
      mtdome: MTDome:0
      mtdometrajectory: MTDomeTrajectory:0
      mtmount: MTMount:0
      mtptg: MTPtg:0
      mtrotator: MTRotator:0
  - name: simonyitel-support
    cscs:
      lasertracker1: LaserTracker:1
      mtaircompressor1: MTAirCompressor:1
      mtaircompressor2: MTAirCompressor:2
