apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "squarebot.fullname" . }}
  labels:
    {{- include "squarebot.labels" . | nindent 4 }}
data:
  SAFIR_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  SAFIR_PATH_PREFIX: {{ .Values.ingress.path | quote }}
  SAFIR_ENVIRONMENT_URL: {{ .Values.global.baseUrl | quote }}
  SQUAREBOT_ENABLE_SCHEMAS: {{ .Values.config.enableSchemas | quote }}
  SQUAREBOT_ENABLE_PRODUCERS: {{ .Values.config.enableProducers | quote }}
  SQUAREBOT_REGISTRY_URL: {{ .Values.config.registryUrl | quote }}
  SQUAREBOT_BROKER_URL: {{ .Values.config.brokerUrl | quote }}
  SQUAREBOT_TOPIC_APP_MENTION: {{ .Values.config.topics.slackAppMention | quote }}
  SQUAREBOT_TOPIC_MESSAGE_CHANNELS: {{ .Values.config.topics.slackMessageChannels | quote }}
  SQUAREBOT_TOPIC_MESSAGE_GROUPS: {{ .Values.config.topics.slackMessageGroups | quote }}
  SQUAREBOT_TOPIC_MESSAGE_IM: {{ .Values.config.topics.slackMessageIm | quote }}
  SQUAREBOT_TOPIC_MESSAGE_MPIM: {{ .Values.config.topics.slackMessageMpim | quote }}
  SQUAREBOT_TOPIC_MESSAGE_INTERACTION: {{ .Values.config.topics.slackInteraction | quote }}
  SQUAREBOT_SLACK_APP_ID: {{ .Values.config.slackAppId | quote }}
