apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "squarebot.fullname" . }}
  labels:
    {{- include "squarebot.labels" . | nindent 4 }}
    app.kubernetes.io/component: "server"
    app.kubernetes.io/part-of: "squarebot"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "squarebot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "squarebot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: "server"
        app.kubernetes.io/part-of: "squarebot"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "squarebot.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "squarebot.fullname" . }}
          env:
            - name: "SQUAREBOT_SLACK_APP_ID"
              valueFrom:
                secretKeyRef:
                  name: {{ template "squarebot.fullname" . }}
                  key: "SQUAREBOT_SLACK_APP_ID"
            - name: "SQUAREBOT_SLACK_SIGNING"
              valueFrom:
                secretKeyRef:
                  name: {{ template "squarebot.fullname" . }}
                  key: "SQUAREBOT_SLACK_SIGNING"
            - name: "SQUAREBOT_SLACK_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: {{ template "squarebot.fullname" . }}
                  key: "SQUAREBOT_SLACK_TOKEN"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
