# Default values for cadc-tap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: "cadc-tap"

# -- Number of pods to start
replicaCount: 1

image:
  # -- tap image to use
  repository: "ghcr.io/lsst-sqre/lsst-tap-service"

  # -- Pull policy for the tap image
  pullPolicy: "IfNotPresent"

  # -- Tag of tap image to use
  # @default -- None, must be provided
  tag: ""

# Settings for the ingress rules.
ingress:
  # -- Additional annotations to use for endpoints that allow anonymous
  # access, such as `/capabilities` and `/availability`
  anonymousAnnotations: {}

  # -- Additional annotations to use for endpoints that are authenticated,
  # such as `/sync`, `/async`, and `/tables`
  authenticatedAnnotations: {}

  # -- External path to the tap service, the path eventually gets rewritten
  # by tomcat.
  path: ""

# -- Resource limits and requests for the Gafaelfawr frontend pod
resources: {}

# -- Annotations for the Gafaelfawr frontend pod
podAnnotations: {}

# -- Node selector rules for the Gafaelfawr frontend pod
nodeSelector: {}

# -- Tolerations for the Gafaelfawr frontend pod
tolerations: []

# -- Affinity rules for the Gafaelfawr frontend pod
affinity: {}

# -- Path to the Vault secret (`secret/k8s_operator/<host>/tap`, for example)
# @default -- None, must be set
vaultSecretsPath: ""

config:
  # -- What type of backend are we connecting to?
  # @default -- None, must be set to "pg" or "qserv"
  backend: ""

  pg:
    # -- Host to connect to
    # @default -- None, must be set if backend is pg
    host: ""

    # -- Database to connect to
    # @default -- None, must be set if backend is pg
    database: ""

    # -- Username to connect with
    # @default -- None, must be set if backend is pg
    username: ""

  qserv:
    # -- Host to connect to
    # @default -- None, must be set if backend is qserv
    host: ""

  # -- Address to a MySQL database containing TAP schema data
  tapSchemaAddress: "cadc-tap-schema-db:3306"

  # -- Datalink payload URL
  datalinkPayloadUrl: "https://github.com/lsst/sdm_schemas/releases/download/1.2.2/datalink-snippets.zip"

  # -- Gafaelfawr hostname to get user information from a token
  # @default -- Value of `ingress.host`
  gafaelfawrHost: ""

  # -- Name of GCS bucket in which to store results
  # @default -- None, must be set
  gcsBucket: ""

  # -- Base URL for results stored in GCS bucket
  # @default -- None, must be set
  gcsBucketUrl: ""

  # -- GCS bucket type (GCS or S3)
  # @default -- GCS
  gcsBucketType: "GCS"

  # -- Java heap size, which will set the maximum size of the heap. Otherwise
  # Java would determine it based on how much memory is available and black
  # maths.
  jvmMaxHeapSize: 4G

  # -- Vault secret name, this is appended to the global path to find the
  # vault secrets associated with this deployment.
  vaultSecretName: ""

qserv:
  # -- QServ hostname:port to connect to
  # @default -- `"mock-qserv:3306"` (the mock QServ)
  host: "mock-qserv:3306"

mockdb:
  # -- Spin up a container to pretend to be the database.
  enabled: true

  image:
    # -- Mock database image to use
    repository: "ghcr.io/lsst-sqre/lsst-tap-mock-qserv"

    # -- Pull policy for the mock database image
    pullPolicy: "IfNotPresent"

    # -- Tag of mock db image to use
    # @default -- Version of TAP image
    tag: ""

  # -- Port to connect to the mock-db on
  port: 3306

  # -- Resource limits and requests for the mock db pod
  resources: {}

  # -- Annotations for the mock db pod
  podAnnotations: {}

  # -- Node selection rules for the mock db pod
  nodeSelector: {}

  # -- Tolerations for the mock db pod
  tolerations: []

  # -- Affinity rules for the mock db pod
  affinity: {}

tapSchema:
  image:
    # -- TAP schema image to ue. This must be overridden by each environment
    # with the TAP schema for that environment.
    repository: "lsstsqre/tap-schema-mock"

    # -- Pull policy for the TAP schema image
    pullPolicy: "IfNotPresent"

    # -- Tag of TAP schema image
    tag: "2.0.2"

  # -- Resource limits and requests for the TAP schema database pod
  resources: {}

  # -- Annotations for the TAP schema database pod
  podAnnotations: {}

  # -- Node selection rules for the TAP schema database pod
  nodeSelector: {}

  # -- Tolerations for the TAP schema database pod
  tolerations: []

  # -- Affinity rules for the TAP schema database pod
  affinity: {}

uws:
  image:
    # -- UWS database image to use
    repository: "ghcr.io/lsst-sqre/lsst-tap-uws-db"

    # -- Pull policy for the UWS database image
    pullPolicy: "IfNotPresent"

    # -- Tag of UWS database image to use
    # @default -- Version of TAP image
    tag: ""

  # -- Resource limits and requests for the UWS database pod
  resources: {}

  # -- Annotations for the UWS databse pod
  podAnnotations: {}

  # -- Node selection rules for the UWS database pod
  nodeSelector: {}

  # -- Tolerations for the UWS database pod
  tolerations: []

  # -- Affinity rules for the UWS database pod
  affinity: {}

# The following will be set by parameters injected by Argo CD and should not
# be set in the individual environment values files.
global:
  # -- Base URL for the environment
  # @default -- Set by Argo CD
  baseUrl: ""

  # -- Host name for ingress
  # @default -- Set by Argo CD
  host: ""

  # -- Base path for Vault secrets
  # @default -- Set by Argo CD
  vaultSecretsPath: ""
