apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrServiceToken
metadata:
  name: "gafaelfawr-token"
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
spec:
  service: "bot-admin-jupyterlab"
  scopes:
    - "admin:jupyterlab"
