apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: "hub"
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
config:
  baseUrl: {{ .Values.global.baseUrl | quote }}
  scopes:
    all:
      - "exec:notebook"
  loginRedirect: true
  delegate:
    notebook: {}
template:
  metadata:
    name: "hub"
  spec:
    rules:
      - host: {{ .Values.global.host | quote }}
        http:
          paths:
            - path: {{ .Values.jupyterhub.hub.baseUrl | quote }}
              pathType: "Prefix"
              backend:
                service:
                  name: "proxy-public"
                  port:
                    name: "http"
