apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: {{ template "nublado.fullname" . }}-hub
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
  namespace: {{ template "nublado.fullname" . }}
config:
  loginRedirect: true
  baseUrl: {{ .Values.global.baseUrl | quote }}
  scopes:
    all:
      - "exec:notebook"
  delegate:
    notebook: {}
template:
  metadata:
    name: {{ template "nublado.fullname" . }}-hub
  spec:
    rules:
      - host: {{ .Values.global.host | quote }}
        http:
          paths:
            - path: {{ .Values.jupyterhub.hub.baseUrl | quote }}
              pathType: "Prefix"
              backend:
                service:
                  name: proxy-public
                  port:
                    name: http
