apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nublado.serviceAccountName" . }}
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.serviceAccountName" . }}
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods","events", "namespaces", "serviceaccounts", "services",
  "persistentvolumeclaims", "persistentvolumes", "resourcequotas",
  "configmaps", "pods/log", "pods/exec", "pods/status"]
  verbs: ["get", "list", "create", "watch", "delete", "update", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "delete", "get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "delete", "get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.serviceAccountName" . }}
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nublado.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "nublado.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.serviceAccountName" . }}
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["create", "delete"]
  - apiGroups: ["apps"]
    resources: ["daemonsets/status"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "nublado.serviceAccountName" . }}
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ template "nublado.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "nublado.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
