kubernetes-replicator:
  serviceAccount:
    create: true
    annotations: {}
    name:
    privileges:
      - apiGroups: ["", "apps", "extensions"]
        resources: ["secrets", "configmaps"]

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000

  podSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
