image:
  repository: ts-dockerhub.lsst.org/rapid-analysis
  tag: c0039
  pullPolicy: Always
env:
  DAF_BUTLER_REPOSITORY_INDEX: /project/data-repos.yaml
  DEPLOY_BRANCH: deploy-tts
siteTag: tts
location: TTS
scripts:
- name: summit/auxTel/runBackgroundService.py
  resources:
    requests:
      cpu: 0.5
      memory: 4G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runButlerWatcher.py
- name: summit/auxTel/runCalibrateCcdRunner.py
- name: summit/auxTel/runImExaminer.py
- name: summit/auxTel/runIsrRunner.py
- name: summit/auxTel/runMetadataCreator.py
- name: summit/auxTel/runMetadataServer.py
- name: summit/auxTel/runMonitor.py
  resources:
    requests:
      cpu: 0.5
      memory: 1G
    limits:
      cpu: 1.0
      memory: 10G
- name: summit/auxTel/runMountTorquePlotter.py
- name: summit/auxTel/runNightReporter.py
- name: summit/auxTel/runSpecExaminer.py
  resources:
    requests:
      cpu: 0.5
      memory: 2G
    limits:
      cpu: 1.0
      memory: 4G
###
### ComCam pods
###
- name: summit/LSSTComCam/runButlerWatcher.py
- name: summit/LSSTComCam/runHeadNode.py
- name: summit/LSSTComCam/runMetadataServer.py
- name: summit/LSSTComCam/runPlotter.py
###
### ComCam StatefulSets
###
comcamWorkerSet:
  name: summit/LSSTComCam/runSfmRunner.py
  replicas: 1
  resources:
    requests:
      cpu: 1.0
      memory: 4G
    limits:
      cpu: 1.0
      memory: 8G
comcamGather2aSet:
  name: summit/LSSTComCam/runStep2aWorker.py
  replicas: 1
  resources:
    requests:
      cpu: 1.0
      memory: "4G"
    limits:
      cpu: 1.0
      memory: "8G"
comcamGatherRollupSet:
  name: summit/LSSTComCam/runNightlyWorker.py
  replicas: 1
  resources:
    requests:
      cpu: 1.0
      memory: "12G"
    limits:
      cpu: 1.0
      memory: "24G"
# TODO: remove google credentials
credentialFile: google_write_creds
vaultPrefixPath: secret/k8s_operator/tucson-teststand.lsst.codes
pullSecretsPath: pull-secret
rubinTvSecretsPath: rubintv
# TODO: remove google credentials
credentialSecretsPath: rubintv
butlerSecret:
  key: butler-secret
  containerPath: /home/saluser/.lsst
  dbUser: oods
imagePullSecrets:
- name: pull-secret
nfsMountpoint:
- name: auxtel-gen3-data
  containerPath: /repo/LATISS
  readOnly: false
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/repo/LATISS
- name: comcam-gen3-data
  containerPath: /repo/LSSTComCam
  readOnly: false
  server: comcam-archiver.tu.lsst.org
  serverPath: /repo/LSSTComCam
- name: auxtel-data
  containerPath: /readonly/lsstdata/auxtel
  readOnly: true
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/lsstdata
- name: comcam-data
  containerPath: /readonly/lsstdata/comcam
  readOnly: true
  server: comcam-archiver.tu.lsst.org
  serverPath: /lsstdata
- name: project-shared
  containerPath: /project
  readOnly: false
  server: nfs-project.tu.lsst.org
  serverPath: /project
- name: auxtel-gen3-data-temp
  containerPath: /data/lsstdata/TTS/auxtel
  readOnly: true
  server: nfs-auxtel.tu.lsst.org
  serverPath: /auxtel/lsstdata/TTS/auxtel
- name: comcam-gen3-data-temp
  containerPath: /data/lsstdata/TTS/comcam
  readOnly: true
  server: comcam-archiver.tu.lsst.org
  serverPath: /lsstdata/TTS/comcam
- name: scratch-shared
  containerPath: /scratch
  readOnly: false
  server: nfs-scratch.tu.lsst.org
  serverPath: /scratch/rubintv
resources:
  requests:
    cpu: 0.5
    memory: 1G
  limits:
    cpu: 1.0
    memory: 2.5G
redis:
  enabled: true
  port: 6379
  env:
    MASTER: true
  envSecrets:
  - name: REDIS_PASSWORD
    secretName: rubintv-secrets
    secretKey: redis-password
  storage:
    classname: rook-ceph-block
    request: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 50Gi
