apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-config
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
data:
  gafaelfawr.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- if .Values.config.updateSchema }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gafaelfawr.fullname" . }}-config-schema-update
  {{- if .Values.config.updateSchema }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    helm.sh/hook-weight: "0"
  {{- end }}
  labels:
    {{- include "gafaelfawr.labels" . | nindent 4 }}
data:
  gafaelfawr.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
