extends: default

ignore:
  - templates
  - shared/charts

rules:
  line-length: disable
  document-start: disable
  indentation:
    spaces: consistent
    indent-sequences: consistent
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
