image:
  pullPolicy: Always
ingress:
  defaultScope: "exec:admin"
config:
  logLevel: "DEBUG"
  databaseUrl: "postgresql://times-square@localhost/times-square"
  githubAppId: "196798"
  enableGitHubApp: "True"
cloudsql:
  enabled: true
  instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
  serviceAccount: "times-square@science-platform-int-dc5d.iam.gserviceaccount.com"
redis:
  persistence:
    storageClass: "premium-rwo"
