replicaCount:
  api: 2
  worker: 2
image:
  pullPolicy: Always
ingress:
  privilegedScope: "exec:notebook"
config:
  logLevel: "DEBUG"
  databaseUrl: "postgresql://timessquare@postgres.postgres/timessquare"
  githubAppId: "327289"
  enableGitHubApp: "True"
cloudsql:
  enabled: false
redis:
  persistence:
    storageClass: "wekafs--sdf-k8s01"
