image:
  pullPolicy: Always
config:
  logLevel: "DEBUG"
  databaseUrl: "postgresql://timessquare@postgres.postgres/timessquare"
  githubAppId: "327289"
  enableGitHubApp: "True"
  worker:
    enableLivenessCheck: false # not compatible with USDF
cloudsql:
  enabled: false
redis:
  persistence:
    storageClass: "wekafs--sdf-k8s01"
