## Default values.yaml for Telegraf Kafka Consumer

# -- Enable Telegraf Kafka Consumer.
# Note that the default configuration is meant to work with InfluxDB v1
# and v2.
enabled: false

image:
  # -- Telegraf image repository.
  repo: "lsstsqre/telegraf"
  # -- Telegraf image tag.
  tag: "avrounions"
  # -- Image pull policy.
  # @default -- IfNotPresent
  pullPolicy: "Always"

# -- Annotations for telegraf-kafka-consumers pods.
podAnnotations: {}

# -- Labels for telegraf-kafka-consumer pods.
podLabels: {}

# -- Secret names to use for Docker pulls.
imagePullSecrets: []

# -- Arguments passed to the Telegraf agent containers.
args: []

# Telegraf agent enviroment variables
env:
  - name: TELEGRAF_PASSWORD
    valueFrom:
      secretKeyRef:
        name: sasquatch
        # -- Telegraf KafkaUser password.
        key: telegraf-password
  - name: INFLUXDB_TOKEN
    valueFrom:
      secretKeyRef:
        name: sasquatch
        # -- InfluxDB v2 admin token.
        key: admin-token
  - name: INFLUXDB_USER
    valueFrom:
      secretKeyRef:
        name: sasquatch
        # -- InfluxDB v1 user
        key: influxdb-user
  - name: INFLUXDB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: sasquatch
        # -- InfluxDB v1 password
        key: influxdb-password


# -- Name of the secret with values to be added to the environment.
envFromSecret: ""

# List of Telegraf Kafka consumers to deploy.
kafkaConsumers:
  test:
    # -- Enable the Telegraf Kafka consumer.
    enabled: false
    # -- Data collection interval for the Kafka consumer.
    interval: "1s"
    # -- Default data flushing interval to InfluxDB.
    flush_interval: "1s"
    # -- Union mode: for Rubin, "nullable" is usually the right choice.
    union_mode: "nullable"
    # -- Avro field that contains the timestamp
    timestamp_field: "private_efdStamp"
    # -- Avro fields to be treated as tags
    tags: []
    # -- Avro fields to be treated as fields.  If not specified,
    # anything that comes in that is not marked as a tag.
    fields: []
    # -- List of regular expressions to specify the Kafka topics consumed by this agent.
    topicRegexps: |
      [ ".*Test" ]

influxdb:
  # -- Name of the InfluxDB v1 database to write to.
  database: "telegraf-kafka-consumer-v1"

influxdb2:
  # -- Name of the InfluxDB v2 bucket to write to.
  bucket: "telegraf-kafka-consumer"

# -- Kubernetes resources requests and limits.
resources: {}

# -- Node labels for pod assignment.
nodeSelector: {}

# -- Affinity for pod assignment.
affinity: {}

# -- Tolerations for pod assignment.
tolerations: []
