apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls
spec:
  secretName: tls

  issuerRef:
    name: "letsencrypt-dns"
    kind: ClusterIssuer

  dnsNames:
    - {{ .Values.ingress.hostname }}
