apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "giftless.fullname" . }}
  labels:
    {{- include "giftless.labels" . | nindent 4 }}
data:
  giftless.conf.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}

