apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "giftless.fullname" . }}
  labels:
    {{- include "giftless.labels" . | nindent 4 }}
data:
  giftless.conf.yaml: |-
    {{- toYaml .Values.config.readonly | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "giftless.fullname" . }}-rw
  labels:
    {{- include "giftless-rw.labels" . | nindent 4 }}
data:
  giftless.conf.yaml: |-
    {{- toYaml .Values.config.readwrite | nindent 4 }}

