apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "giftless.fullname" . }}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - {{ .Values.ingress.hostname | quote }}
    secretName: tls
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - backend:
          service:
            name: giftless
            port:
              number: 5000
        path: /
        pathType: Prefix
