apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nublado.fullname" . }}-config
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
data:
  config.yaml: |-
  {{- toYaml .Values.controller | nindent 4 }}
    global:
    {{- toYaml .Values.global | nindent 6 }}

