apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nublado.fullname" . }}-config
  labels:
    {{- include "nublado.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.controller | nindent 2 }}
  global:
    {{- toYaml .Values.global | nindent 4 }}
