apiVersion: v1
kind: ConfigMap
metadata:
  name: siav2-config
  labels:
    {{- include "siav2.labels" . | nindent 4 }}
data:
  cadc-registry.properties: |
    ivo://ivoa.net/sso#OpenID = {{ .Values.global.baseUrl }}/auth/openid
  catalina.properties: |
    # tomcat properties
    tomcat.connector.connectionTimeout=20000
    tomcat.connector.keepAliveTimeout=120000
    tomcat.connector.secure=false
    tomcat.connector.scheme=http
    tomcat.connector.proxyName={{ .Values.global.host }}
    tomcat.connector.proxyPort=8080

    # database connection pools for uws
    org.opencadc.sia2.uws.maxActive=5
    org.opencadc.sia2.uws.username=postgres
    org.opencadc.sia2.uws.password=
    org.opencadc.sia2.uws.url=jdbc:postgresql://siav2-uws-db/

    # authentication provider
    # ca.nrc.cadc.auth.IdentityManager=org.opencadc.auth.StandardIdentityManager
  sia2.properties: |
    # TAP service
    org.opencadc.sia2.queryService = {{ .Values.global.baseUrl }}/api/tap
  war-rename.conf: |
    mv sia2.war api#siav2.war
