---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ .Values.global.controlSystem.appNamespace }}
spec:
  path: {{ .Values.global.vaultSecretsPath }}/{{ .Values.global.controlSystem.appNamespace }}
  type: Opaque
{{- range $secret := .Values.pullSecrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $secret.name }}
spec:
  path: {{ $.Values.global.vaultSecretsPath }}/pull-secret
  type: kubernetes.io/dockerconfigjson
{{- end }}
