cadc-tap:
  config:
    pg:
      image:
        repository: "ghcr.io/lsst-sqre/tap-postgres-service"
        pullPolicy: "Always"
        tag: "1.16.0"

  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfdev-sso"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-dev-7696:us-central1:science-platform-dev-e9e11de2"
    serviceAccount: "ssotap@science-platform-dev-7696.iam.gserviceaccount.com"
    database: "ssotap"
