# -- Set the replica count for the LOVE producers
replicaCount: 1
image:
  # -- The LOVE producer image to use
  repository: lsstts/love-producer
  # str -- The tag to use for the LOVE producer image
  tag:
  # -- The pull policy on the LOVE producer image
  pullPolicy: IfNotPresent
# -- This section holds a set of key, value pairs for environmental variables
env:
  WEBSOCKET_HOST: love-nginx/manager/ws/subscription
# -- This section holds a set of key, value pairs for secrets
envSecrets:
  PROCESS_CONNECTION_PASS: process-connection-pass
# -- This sections sets the list of producers to use.
# The producers should be specified like:
# _name_: _CSC name:index_
# Example: ataos: ATAOS:0
producers: {}
# -- This allows the specification of pod annotations.
podAnnotations: {}
# -- Resource specifications for the LOVE producer pods
resources: {}
# -- Node selection rules for the LOVE producer pods
nodeSelector: {}
# -- Toleration specifications for the LOVE producer pods
tolerations: []
# -- Affinity rules for the LOVE producer pods
affinity: {}
