# Default values for HSC prompt-proto-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prompt-proto-service:

  # -- Annotations for the prompt-proto-service pod
  podAnnotations:
    autoscaling.knative.dev/min-scale: "3"
    autoscaling.knative.dev/max-scale: "100"
    autoscaling.knative.dev/target-utilization-percentage: "60"
    autoscaling.knative.dev/target-burst-capacity: "-1"
    # Update this field if `make apply` by itself doesn't make a new revision.
    revision: "1"

  image:
    repository: ghcr.io/lsst-dm/prompt-proto-service
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    name: HSC
    pipelines: (survey="SURVEY")=[${PROMPT_PROTOTYPE_DIR}/pipelines/${RUBIN_INSTRUMENT}/ApPipe.yaml]
    skymap: hsc_rings_v1
    calibRepo: ""

  s3:
    imageBucket: ""
    endpointUrl: ""
    auth_env: true
    disableBucketValidation: ""

  imageNotifications:
    kafkaClusterAddress: ""
    topic: ""
    imageTimeout: '120'

  apdb:
    ip: ""
    db: lsst-devl
    user: rubin
    namespace: pp_apdb

  registry:
    ip: ""
    db: ppcentralbutler
    user: pp

  knative:
    ephemeralStorageRequest: "8Gi"
    ephemeralStorageLimit: "20Gi"
    timeout: 900
    idleTimeout: 900
    responseStartTimeout: 900

  vaultSecretsPath: ""
