{{- if .Values.entrypoint }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.name" . }}-entrypoint
  namespace: {{ .Values.namespace }}
data:
  .startup.sh:
{{ .Values.entrypoint | toYaml | indent 4 }}
{{- end }}
