butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-dev-repos.yaml"
fqdn: data-dev.lsst.cloud
name: idfdev
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data-dev.lsst.cloud

applications:
  argo-workflows:
    enabled: true
  datalinker:
    enabled: true
  hips:
    enabled: true
  mobu:
    enabled: true
  noteburst:
    enabled: true
  nublado:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  sasquatch:
    enabled: true
  semaphore:
    enabled: true
  sherlock:
    enabled: true
  ssotap:
    enabled: true
  squareone:
    enabled: true
  sqlproxy-cross-project:
    enabled: true
  strimzi:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
  telegraf:
    enabled: true
  telegraf-ds:
    enabled: true
  times-square:
    enabled: true
  vault-secrets-operator:
    enabled: true
  vo-cutouts:
    enabled: true
