environment: usdfdev-ap
fqdn: alert-stream-broker.slac.stanford.edu
vaultPathPrefix: secret/rubin/usdf-alert-stream-broker-dev
# butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
repoURL: https://github.com/lsst-sqre/phalanx.git

alert-stream-broker:
  enabled: true
cert-manager:
  enabled: true
ingress-nginx:
  enabled: true
strimzi:
  enabled: true
strimzi-access-operator:
  enabled: true
strimzi-registry-operator:
  enabled: true