butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-dev-repos.yaml"
environment: idfdev
fqdn: data-dev.lsst.cloud
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data-dev.lsst.cloud

alert-stream-broker:
  enabled: false
argo-workflows:
  enabled: true
cachemachine:
  enabled: false
cert-manager:
  enabled: true
datalinker:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
hips:
  enabled: true
ingress-nginx:
  enabled: true
kubernetes-replicator:
  enabled: false
mobu:
  enabled: true
moneypenny:
  enabled: false
monitoring:
  enabled: false
narrativelog:
  enabled: false
noteburst:
  enabled: true
nublado:
  enabled: true
nublado2:
  enabled: false
ook:
  enabled: false
plot-navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
sasquatch:
  enabled: true
production-tools:
  enabled: false
semaphore:
  enabled: true
sherlock:
  enabled: true
ssotap:
  enabled: true
squareone:
  enabled: true
squarebot:
  enabled: false
squash-api:
  enabled: false
sqlproxy-cross-project:
  enabled: true
strimzi:
  enabled: true
strimzi-access-operator:
  enabled: false
tap:
  enabled: true
tap-schema:
  enabled: true
telegraf:
  enabled: true
telegraf-ds:
  enabled: true
times-square:
  enabled: true
vault-secrets-operator:
  enabled: true
vo-cutouts:
  enabled: true
