butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-dev-repos.yaml"
fqdn: data-dev.lsst.cloud
name: idfdev
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data-dev.lsst.cloud

applications:
  argo-workflows: true
  datalinker: true
  hips: true
  mobu: true
  noteburst: true
  nublado: true
  portal: true
  postgres: true
  sasquatch: true
  semaphore: true
  sherlock: true
  ssotap: true
  squareone: true
  sqlproxy-cross-project: true
  strimzi: true
  tap: true
  tap-schema: true
  telegraf: true
  telegraf-ds: true
  times-square: true
  vault-secrets-operator: true
  vo-cutouts: true
