butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
fqdn: data.lsst.cloud
name: idfprod
onepassword:
  connectUrl: "https://roundtable.lsst.cloud/1password"
  vaultTitle: "RSP data.lsst.cloud"
vaultPathPrefix: secret/phalanx/idfprod

applications:
  datalinker: true
  hips: true
  mobu: true
  nublado: true
  portal: true
  semaphore: true
  sherlock: true
  siav2: true
  squareone: true
  ssotap: true
  tap: true
  telegraf: true
  telegraf-ds: true
  vo-cutouts: true
