butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-int-repos.yaml"
fqdn: data-int.lsst.cloud
name: idfint
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data-int.lsst.cloud

applications:
  alert-stream-broker:
    enabled: true
  cachemachine:
    enabled: true
  datalinker:
    enabled: true
  hips:
    enabled: true
  linters:
    enabled: true
  mobu:
    enabled: true
  moneypenny:
    enabled: true
  nublado:
    enabled: true
  nublado2:
    enabled: true
  plot-navigator:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  sasquatch:
    enabled: true
  ssotap:
    enabled: true
  production-tools:
    enabled: true
  semaphore:
    enabled: true
  sherlock:
    enabled: true
  squareone:
    enabled: true
  strimzi:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
  telegraf:
    enabled: true
  telegraf-ds:
    enabled: true
  vo-cutouts:
    enabled: true
