environment: idfdev
fqdn: data-dev.lsst.cloud
vaultPathPrefix: secret/k8s_operator/data-dev.lsst.cloud
butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-int-repos.yaml"

alert-stream-broker:
  enabled: false
cachemachine:
  enabled: false
cert-manager:
  enabled: true
datalinker:
  enabled: true
exposurelog:
  enabled: false
gafaelfawr:
  enabled: true
  revision: tickets/DM-37390
hips:
  enabled: true
ingress-nginx:
  enabled: true
mobu:
  enabled: true
moneypenny:
  enabled: false
narrativelog:
  enabled: false
noteburst:
  enabled: true
nublado:
  enabled: true
  revision: tickets/DM-36570
nublado2:
  enabled: false
plot-navigator:
  enabled: false
portal:
  enabled: true
postgres:
  enabled: true
sasquatch:
  enabled: true
production-tools:
  enabled: false
semaphore:
  enabled: true
sherlock:
  enabled: true
squareone:
  enabled: true
squash-api:
  enabled: false
sqlproxy-cross-project:
  enabled: true
strimzi:
  enabled: true
strimzi-registry-operator:
  enabled: false
tap:
  enabled: true
tap-schema:
  enabled: true
telegraf:
  enabled: true
telegraf-ds:
  enabled: true
times-square:
  enabled: true
vault-secrets-operator:
  enabled: true
vo-cutouts:
  enabled: true
