name: ccin2p3
fqdn: data-dev.lsst.eu
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/rsp-cc

applications:
  cachemachine:
    enabled: true
  datalinker:
    enabled: true
  moneypenny:
    enabled: true
  nublado2:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  squareone:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
