fqdn: k8s.slac.stanford.edu/usdf-prompt-processing-dev
name: usdfdev-prompt-processing
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: secret/rubin/usdf-prompt-processing-dev

applications:
  prompt-proto-service-hsc: true
  prompt-proto-service-latiss: true
  prompt-proto-service-lsstcam: false
  prompt-proto-service-lsstcomcam: false
