butlerRepositoryIndex: "s3://rubin-summit-users/data-repos.yaml"
fqdn: usdf-rsp.slac.stanford.edu
name: usdfprod
vaultUrl: "https://vault.slac.stanford.edu"
vaultPathPrefix: secret/rubin/usdf-rsp

applications:
  # This environment uses an ingress managed in a separate Kubernetes cluster,
  # despite that configuration not being officially supported by Phalanx.
  cert-manager:
    enabled: false
  ingress-nginx:
    enabled: false

  cachemachine:
    enabled: true
  datalinker:
    enabled: true
  livetap:
    enabled: true
  mobu:
    enabled: true
  moneypenny:
    enabled: true
  nublado:
    enabled: true
  nublado2:
    enabled: true
  plot-navigator:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  sasquatch:
    enabled: true
  semaphore:
    enabled: true
  ssotap:
    enabled: true
  squareone:
    enabled: true
  strimzi:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
