name: "summit"
fqdn: "summit-lsp.lsst.codes"
appOfAppsName: "science-platform"
vaultPathPrefix: "secret/k8s_operator/summit-lsp.lsst.codes"

applications:
  consdb: true
  exposurelog: true
  narrativelog: true
  nightreport: true
  nublado: true
  portal: true
  postgres: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
