name: roundtable-prod
fqdn: roundtable.lsst.cloud
onepassword:
  connectUrl: "https://roundtable.lsst.cloud/1password"
  vaultTitle: "RSP roundtable.lsst.cloud"
vaultPathPrefix: secret/phalanx/roundtable-prod

applications:
  kubernetes-replicator: true
  onepassword-connect: true
  ook: true
  sasquatch: true
  squareone: true
  strimzi: true
  strimzi-access-operator: true
  squarebot: true
