name: roundtable-dev
fqdn: roundtable-dev.lsst.cloud
onepassword:
  connectUrl: "https://roundtable-dev.lsst.cloud/1password"
  vaultTitle: "RSP roundtable-dev.lsst.cloud"
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/phalanx/roundtable-dev

applications:
  giftless: true
  kubernetes-replicator: true
  monitoring: true
  onepassword-connect: true
  ook: true
  sasquatch: true
  squarebot: true
  squareone: true
  strimzi: true
  strimzi-access-operator: true
