name: tucson-teststand
fqdn: tucson-teststand.lsst.codes
vaultPathPrefix: secret/k8s_operator/tucson-teststand.lsst.codes

applications:
  argo-workflows: true
  auxtel: true
  calsys: true
  control-system-test: true
  dmocps: true
  eas: true
  exposurelog: true
  narrativelog: true
  nublado: true
  obssys: true
  portal: true
  sasquatch: true
  simonyitel: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true
