name: minikube
fqdn: minikube.lsst.codes
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/minikube.lsst.codes

# The primary constraint on enabling applications is the low available memory
# of a GitHub Actions runner, since minikube is used for smoke testing of new
# Helm configurations.
applications:
  datalinker:
    enabled: true
  gafaelfawr:
    enabled: true
  hips:
    enabled: true
  mobu:
    enabled: true
  postgres:
    enabled: true
  squareone:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
