name: "base"
fqdn: "base-lsp.lsst.codes"
appOfAppsName: "science-platform"
onepassword:
  connectUrl: "https://roundtable.lsst.cloud/1password"
  vaultTitle: "RSP base-lsp.lsst.codes"
vaultPathPrefix: "secret/phalanx/base"

applications:
  argo-workflows: true
  consdb: true
  exposurelog: true
  mobu: true
  narrativelog: true
  nightreport: true
  nublado: true
  portal: true
  rubintv: true
  sasquatch: true
  squareone: true
  strimzi: true
  telegraf: true
  telegraf-ds: true

controlSystem:
  imageTag: "k0001"
  siteTag: "base"
  s3EndpointUrl: "https://s3.ls.lsst.org"
