butlerRepositoryIndex: "s3://butler-us-central1-repo-locations/data-repos.yaml"
fqdn: data.lsst.cloud
name: idfprod
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/data.lsst.cloud

applications:
  datalinker:
    enabled: true
  hips:
    enabled: true
  mobu:
    enabled: true
  nublado:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  semaphore:
    enabled: true
  sherlock:
    enabled: true
  squareone:
    enabled: true
  ssotap:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
  telegraf:
    enabled: true
  telegraf-ds:
    enabled: true
  vo-cutouts:
    enabled: true
