name: roundtable-dev
fqdn: roundtable-dev.lsst.cloud
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/roundtable-dev.lsst.cloud

applications:
  giftless:
    enabled: true
  kubernetes-replicator:
    enabled: true
  monitoring:
    enabled: true
  ook:
    enabled: true
  sasquatch:
    enabled: true
  squarebot:
    enabled: true
  squareone:
    enabled: true
  strimzi:
    enabled: true
  strimzi-access-operator:
    enabled: true
