environment: usdfdev-alert-stream-broker
#fqdn: alert-stream-broker.slac.stanford.edu
vaultPathPrefix: secret/rubin/usdf-alert-stream-broker-dev
repoURL: https://github.com/lsst-sqre/phalanx.git

alert-stream-broker:
  enabled: true
cert-manager:
  enabled: true
ingress-nginx:
  enabled: false
strimzi:
  enabled: true
strimzi-access-operator:
  enabled: false
strimzi-registry-operator:
  enabled: true