name: roe
fqdn: rsp.lsst.ac.uk
vaultUrl: "https://vault.lsst.codes"
vaultPathPrefix: secret/k8s_operator/roe

applications:
  cachemachine:
    enabled: true
  mobu:
    enabled: true
  moneypenny:
    enabled: true
  nublado2:
    enabled: true
  portal:
    enabled: true
  postgres:
    enabled: true
  squareone:
    enabled: true
  tap:
    enabled: true
  tap-schema:
    enabled: true
