# These four settings should be set in each environment values-*.yaml file.

# -- Butler repository index to use for this environment
# @default -- None, must be set
butlerRepositoryIndex: ""

# -- Name of the environment
# @default -- None, must be set
name: ""

# -- Fully-qualified domain name where the environment is running
# @default -- None, must be set
fqdn: ""

# -- UUID of the 1Password item in which to find Vault tokens
onepasswordUuid: "dg5afgiadsffeklfr6jykqymeu"

# -- URL of the repository for all applications
repoUrl: https://github.com/lsst-sqre/phalanx.git

# -- Revision of repository to use for all applications
targetRevision: "main"

# -- URL of Vault server for this environment
# @default -- None, must be set
vaultUrl: ""

# -- Prefix for Vault secrets for this environment
# @default -- None, must be set
vaultPathPrefix: ""

applications:
  alert-stream-broker:
    # -- Enable the alert-stream-broker application
    enabled: false

  argo-workflows:
    # -- Enable the argo-workflows application
    enabled: false

  argocd:
    # -- Enable the Argo CD application. This must be enabled for all
    # environments and is present here only because it makes parsing easier
    enabled: true

  cachemachine:
    # -- Enable the cachemachine application (required by nublado2)
    enabled: false

  cert-manager:
    # -- Enable the cert-manager application, required unless the environment
    # makes separate arrangements to inject a current TLS certificate
    enabled: true

  datalinker:
    # -- Eanble the datalinker application
    enabled: false

  exposurelog:
    # -- Enable the exposurelog application
    enabled: false

  gafaelfawr:
    # -- Enable the Gafaelfawr application. This is required by Phalanx since
    # most other applications use `GafaelfawrIngress`
    enabled: true

  giftless:
    # -- Enable the giftless application
    enabled: false

  hips:
    # -- Enable the HiPS application
    enabled: false

  ingress-nginx:
    # -- Enable the ingress-nginx application. This is required for all
    # environments, but is still configurable because currently USDF uses an
    # unsupported configuration with ingress-nginx deployed in a different
    # cluster.
    enabled: true

  kubernetes-replicator:
    # -- Enable the kubernetes-replicator application
    enabled: false

  linters:
    # -- Enable the linters application
    enabled: false

  livetap:
    # -- Enable the livetap application
    enabled: false

  mobu:
    # -- Enable the mobu application
    enabled: false

  moneypenny:
    # -- Enable the moneypenny application (required by nublado2)
    enabled: false

  monitoring:
    # -- Enable the monitoring application
    enabled: false

  narrativelog:
    # -- Enable the narrativelog application
    enabled: false

  noteburst:
    # -- Enable the noteburst application (required by times-square)
    enabled: false

  nublado:
    # -- Enable the nublado application (v3 of the Notebook Aspect)
    enabled: false

  nublado2:
    # -- Enable the nublado2 application (v2 of the Notebook Aspect, now
    # deprecated). This should not be used for new environments.
    enabled: false

  ook:
    # -- Enable the ook application
    enabled: false

  obsloctap:
    # -- Enable the obsloctap application
    enabled: false

  plot-navigator:
    # -- Enable the plot-navigator application
    enabled: false

  portal:
    # -- Enable the portal application
    enabled: false

  postgres:
    # -- Enable the in-cluster PostgreSQL server. Use of this server is
    # discouraged in favor of using infrastructure SQL, but will remain
    # supported for use cases such as minikube test deployments.
    enabled: false

  sasquatch:
    # -- Enable the sasquatch application
    enabled: false

  ssotap:
    # -- Enable the ssotap application
    enabled: false

  production-tools:
    # -- Enable the production-tools application
    enabled: false

  semaphore:
    # -- Enable the semaphore application
    enabled: false

  sherlock:
    # -- Enable the sherlock application
    enabled: false

  sqlproxy-cross-project:
    # -- Enable the sqlproxy-cross-project application
    enabled: false

  squarebot:
    # -- Enable the squarebot application
    enabled: false

  squareone:
    # -- Enable the squareone application
    enabled: false

  squash-api:
    # -- Enable the squash-api application
    enabled: false

  strimzi:
    # -- Enable the strimzi application
    enabled: false

  strimzi-access-operator:
    # -- Enable the strimzi-access-operator application
    enabled: false

  tap:
    # -- Enable the tap application
    enabled: false

  tap-schema:
    # -- Enable the tap-schema application
    enabled: false

  telegraf:
    # -- Enable the telegraf application
    enabled: false

  telegraf-ds:
    # -- Enable the telegraf-ds application
    enabled: false

  times-square:
    # -- Enable the times-square application
    enabled: false

  vault-secrets-operator:
    # -- Enable the vault-secrets-operator application. This is required for
    # all environments.
    enabled: true

  vo-cutouts:
    # -- Enable the vo-cutouts application
    enabled: false
