apiVersion: v1
kind: Service
metadata:
  name: "butler-example-service"
  labels:
    {{- include "butler-example-service.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "butler-example-service.selectorLabels" . | nindent 4 }}
