prompt-proto-service:

  podAnnotations:
    # Update this field if using latest or static image tag in dev
    revision: "1"

  image:
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest

  instrument:
    pipelines:
      main: >-
        (survey="SURVEY")=[${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/ApPipe.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/SingleFrame.yaml,
        ${PROMPT_PROCESSING_DIR}/pipelines/LSSTComCamSim/Isr.yaml]
      preprocessing: (survey="SURVEY")=[]
    calibRepo: s3://repo-test-users/repotest02/

  s3:
    imageBucket: repo-test
    endpointUrl: https://sdfembs3.sdf.slac.stanford.edu
    cred_file_auth: True
    # do not set AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID. Use cred file
    auth_env: False
    aws_profile: embargo

  imageNotifications:
    kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
    topic: repo-test

  apdb:
    config: s3://repo-test-users/apdb_config/pp_apdb_lsstcomcamsim-dev.py

  sasquatch:
    endpointUrl: https://usdf-rsp-dev.slac.stanford.edu/sasquatch-rest-proxy
    auth_env: false

  fullnameOverride: "prompt-proto-service-lsstcomcamsim"
