{{- range $producer, $csc := .Values.producers }}
{{ $appName := printf "%s-%s" $.Release.Name $producer | trunc 63 | trimSuffix "-" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}
  labels:
    {{- include "love-producer.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "love-producer.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/instance: {{ $appName }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      labels:
        {{- include "love-producer.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/instance: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}
          {{- $imageTag := $.Values.image.tag | default $.Values.global.controlSystemImageTag }}
          image: "{{ $.Values.image.repository }}:{{ $imageTag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
            name: csc-env-config
          - secretRef:
            name: ts-salkafka
          env:
            - name: LOVE_CSC_PRODUCER
              value: {{ $csc | quote }}
          {{- range $env_var, $env_value := $.Values.env }}
            - name: {{ $env_var }}
              value: {{ $env_value | quote }}
          {{- end }}
          {{- range $env_var, $env_value := $.Values.envSecrets }}
            - name: {{ $env_var }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.namespace }}-secrets
                  key: {{ $env_value }}
          {{- end }}
          {{- with $.Values.resources }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- end }}
      imagePullSecrets:
        - name: nexus3-docker
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml $ | nindent 8 }}
      {{- end }}
{{- end }}
