vault-secrets-operator:
  environmentVars:
    - name: "VAULT_ROLE_ID"
      valueFrom:
        secretKeyRef:
          name: "vault-credentials"
          key: "VAULT_ROLE_ID"
    - name: "VAULT_SECRET_ID"
      valueFrom:
        secretKeyRef:
          name: "vault-credentials"
          key: "VAULT_SECRET_ID"
    # Set the token lifetime to six hours to minimize the spam of
    # not-yet-expired tokens in Vault from GitHub Actions CI tests.
    - name: "VAULT_TOKEN_MAX_TTL"
      value: "21600"
  vault:
    authMethod: "approle"
