image:
  tag: "tickets-DM-38408"
  pullPolicy: "Always"
config:
  useCachemachine: false
  autostart:
    - name: "python"
      count: 1
      users:
        - username: "bot-mobu-user"
      scopes: ["exec:notebook"]
      business:
        type: "JupyterPythonLoop"
        options:
          image:
            image_class: "latest-weekly"
            size: "Small"
        restart: true
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        options:
          query_set: "dp0.2"
        restart: true
