config:
  debug: true
  githubRefreshApp:
    acceptedGithubOrgs:
      - lsst-sqre
  autostart:
    - name: "firefighter"
      count: 1
      users:
        - username: "bot-mobu03"
          uidnumber: 45694
          gidnumber: 1126
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          image:
            image_class: "latest-weekly"
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_ref: "prod"
        restart: true
    - name: "dfuchs-test"
      count: 1
      users:
        - username: "bot-mobu-dfuchs-test"
      scopes:
        - "exec:notebook"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/dfuchs-test-mobu.git"
          repo_ref: "exceptions"
        restart: true
