config:
  githubRefreshApp:
    acceptedGithubOrgs:
      - lsst-sqre
  autostart:
    - name: "firefighter"
      count: 5
      user_spec:
        username_prefix: "bot-mobu-recommended"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_ref: "prod"
          max_executions: 1
        restart: true
    - name: "quickbeam"
      count: 1
      users:
        - username: "bot-mobu-persistent"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_ref: "prod"
          idle_time: 900
          delete_lab: false
        restart: true
    - name: "tutorial"
      count: 1
      users:
        - username: "bot-mobu-tutorial"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/rubin-dp0/tutorial-notebooks.git"
          repo_ref: "prod"
          max_executions: 1
          working_directory: "notebooks/tutorial-notebooks"
        restart: true
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQuerySetRunner"
        options:
          query_set: "dp0.2"
        restart: true
    - name: "dfuchs-test"
      count: 1
      users:
        - username: "bot-mobu-dfuchs-test"
      scopes:
        - "exec:notebook"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/dfuchs-test-mobu.git"
          repo_ref: "exceptions"
        restart: true
