config:
  debug: true
  autostart:
    - name: "nublado2"
      count: 1
      users:
        - username: "bot-mobu-user"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          image:
            image_class: "latest-weekly"
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
        restart: true
    - name: "weekly"
      count: 1
      users:
        - username: "bot-mobu-weekly"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          image:
            image_class: "latest-weekly"
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
          url_prefix: "/n3"
          use_cachemachine: false
        restart: true
    - name: "tutorial"
      count: 1
      users:
        - username: "bot-mobu-tutorial"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/rubin-dp0/tutorial-notebooks.git"
          repo_branch: "prod"
          max_executions: 1
          working_directory: "notebooks/tutorial-notebooks"
          use_cachemachine: false
          url_prefix: "/n3"
        restart: true
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQueryRunner"
        options:
          query_set: "dp0.2"
        restart: true
