config:
  debug: true
  autostart:
    - name: "gitlfs"
      count: 1
      users:
        - username: "bot-mobu-gitlfs"
      scopes:
        - "write:git-lfs"
      business:
        type: "GitLFS"
        options:
          lfs_read_url: "https://git-lfs-dev.lsst.cloud/mobu/git-lfs-test"
          lfs_write_url: "https://git-lfs-dev-rw.lsst.cloud/mobu/git-lfs-test"
        restart: true
    - name: "dfuchs-test"
      count: 1
      users:
        - username: "bot-mobu-dfuchs-test"
      scopes:
        - "exec:notebook"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/dfuchs-test-mobu.git"
          repo_ref: "exceptions"
        restart: true
