config:
  debug: true
  autostart:
    - name: "recommended"
      count: 1
      users:
        - username: "bot-mobu-recommended"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/lsst-sqre/system-test.git"
          repo_branch: "prod"
          exclude_dirs: ["experiments"]
        restart: true
    - name: "tutorial"
      count: 1
      users:
        - username: "bot-mobu-tutorial"
      scopes:
        - "exec:notebook"
        - "exec:portal"
        - "read:image"
        - "read:tap"
      business:
        type: "NotebookRunner"
        options:
          repo_url: "https://github.com/rubin-dp0/tutorial-notebooks.git"
          repo_branch: "prod"
          exclude_dirs: ["DP02_09_Custom_Coadds", "DP02_11_User_Packages"]
          max_executions: 1
          working_directory: "notebooks/tutorial-notebooks"
        restart: true
    - name: "tap"
      count: 1
      users:
        - username: "bot-mobu-tap"
      scopes: ["read:tap"]
      business:
        type: "TAPQuerySetRunner"
        options:
          query_set: "dp0.2"
        restart: true
