apiVersion: v1
kind: Service
metadata:
  name: internal-butler
spec:
  selector:
    {{- include "plot-navigator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: butler
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
