apiVersion: apps/v1
kind: Deployment
metadata:
  name: plot-navigator
  labels:
    {{- include "plot-navigator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "plot-navigator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plot-navigator.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        {{- with .Values.config.volumes }}
        {{- . | toYaml | nindent 8 }}
        {{- end }}
      containers:
      - name: plot-navigator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}
        imagePullPolicy: Always
        env:
{{- range $key, $value := .Values.environment }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
{{- end }}
          - name: S3_KEY
            valueFrom:
              secretKeyRef:
                name: {{ include "plot-navigator.fullname" . }}
                key: S3_KEY
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ include "plot-navigator.fullname" . }}
                key: S3_SECRET
        {{- if .Values.config.envFromSecretPath }}
        envFrom:
          - secretRef: {{ include "plot-navigator.fullname" . }}
        {{- end }}
        {{- if .Values.config.volume_mounts }}
        volumeMounts:
          {{- with .Values.config.volume_mounts }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
        {{- end }}
