---
apiVersion: v1
kind: ConfigMap
metadata:
  name: instrument-map
data:
  instruments: |
    knative-urls:
      {{- .Values.knativeUrls | toYaml | nindent 6 }}
    detectors:
      {{- .Values.detectorConfig | toYaml | nindent 6 }}
