image:
  pullPolicy: Always

config:
  dp02PostgresUri: postgresql://postgres@sqlproxy-butler-int.sqlproxy-cross-project:5432/dp02
  s3EndpointUrl: "https://storage.googleapis.com"
  repositories:
    dp02: "file:///opt/lsst/butler/config/dp02.yaml"
    ir2: "s3://butler-us-central1-panda-dev/ir2/butler-ir2.yaml"
