{{- if (index .Values "argo-workflows" "enabled") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
spec:
  finalizers:
    - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argo-workflows"
  namespace: "argo-workflows"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "argo"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "applications/argo-workflows"
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.environment }}.yaml"
{{- end -}}
