{{- if (index .Values "applications"  "prompt-proto-service-hsc") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: next-visit-fan-out
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: next-visit-fan-out
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/next-visit-fan-out
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}