{{- if .Values.applications.nublado -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "nublado-fileservers"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "nublado-fileservers"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "nublado-fileservers"
    server: "https://kubernetes.default.svc"
  project: "default"
  source:
    path: "applications/nublado-fileservers"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
{{- end -}}
