{{- if (index .Values "prompt-processing-hsc" "enabled") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prompt-processing-hsc
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
    syncPolicy:
      managedNamespaceMetadata:
        labels:
          argocd.argoproj.io/managed-by: argocd
      syncOptions:
      - CreateNamespace=true
  destination:
    namespace: prompt-proto-service-hsc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/prompt-proto-service
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      #parameters:
      #- name: "imageNotifications.imageTimeout"
      #  forceString: true
      valueFiles:
        - values-{{ .Values.environment }}-hsc.yaml
{{- end -}}


{{- if (index .Values "prompt-processing-latiss" "enabled") -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prompt-processing-latiss
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    syncOptions:
    - CreateNamespace=true
  destination:
    namespace: prompt-proto-service-latiss
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/prompt-proto-service
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    helm:
      valueFiles:
        - values-{{ .Values.environment }}-latiss.yaml
{{- end -}}

