apiVersion: v2
appVersion: 0.1.0
description: Dashboard for examination of scheduler snapshots.
name: schedview-snapshot
sources:
- https://github.com/lsst-sqre/schedview-snapshot
type: application
version: 1.0.0
