---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $.Values.envSecretKeyName }}-secrets
  namespace: {{ $.Values.global.controlSystemAppNamespace }}
spec:
  path: {{ $.Values.global.vaultSecretsPath }}/{{ $.Values.envSecretKeyName }}
  type: Opaque
