{{- range $secret := .Values.secrets }}
---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Values.namespace }}
spec:
  path: {{ $.Values.global.vaultSecretsPath }}/{{ $secret.key }}
  type: {{ default "Opaque" $secret.type }}
{{- end }}
