ingress-nginx:
  controller:
    config:
      error-log-level: "error"
      large-client-header-buffers: "4 64k"
      proxy-buffer-size: "64k"
    service:
      type: NodePort
      ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
        - port: 443
          targetPort: 443
          nodePort: 30443
