config:
  influxdbHostname: "monitoring.lsst.cloud"
  influxdbOrg: "square"
chronograf:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard-rwo
  env:
    INFLUX_DB_URL: "monitoring.lsst.cloud"
    GH_CLIENT_ID: "e85fe410b0021a251180"
cronjob:
  enabled: true
  debug: true
ingress:
  enabled: true
  chronograf:
    hostname: "panopticon-dev.lsst.cloud"
