config:
  influxdbHostname: "monitoring.lsst.cloud"
  influxdbOrg: "square"
influxdb2:
  enabled: true
  # -- Schedule onto the kafka pool
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "kafka"
    effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "roundtable.lsst.cloud/pool"
            operator: "In"
            values:
            - "kafka"
chronograf:
  enabled: true
  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard-rwo
  env:
    INFLUX_DB_URL: "monitoring.lsst.cloud"
    GH_CLIENT_ID: "e85fe410b0021a251180"

ingress:
  enabled: true
  chronograf:
    hostname: "panopticon.lsst.cloud"
  influxdb2:
    hostname: "monitoring.lsst.cloud"
