apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fileserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: fileservers
    server: https://kubernetes.default.svc
  project: default
  source:
    path: applications/nublado/charts/fileserver
    repoURL: https://github.com/lsst-sqre/phalanx.git
    targetRevision: tickets/DM-38972
