strimzi-kafka:
  mirrormaker2:
    enabled: true
    source:
      bootstrapServer: sasquatch-summit-kafka-bootstrap.lsst.codes:9094
      topicsPattern: "lsst.sal.Test.*, registry-schemas"
    replication:
      policy:
        separator: "."
        class: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
    sourceRegistry:
      enabled: true
      schemaTopic: source.registry-schemas
    sourceConnect:
      enabled: true
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
  kafka:
    storage:
      storageClassName: rook-ceph-block
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: "139.229.153.65"
        host: sasquatch-base-kafka-bootstrap.lsst.codes
      brokers:
        - loadBalancerIP: "139.229.153.66"
          host: sasquatch-base-kafka-0.lsst.codes
        - loadBalancerIP: "139.229.153.67"
          host: sasquatch-base-kafka-1.lsst.codes
        - loadBalancerIP: "139.229.153.68"
          host: sasquatch-base-kafka-2.lsst.codes
  zookeeper:
    storage:
      storageClassName: rook-ceph-block
  users:
    replicator:
      enabled: true

influxdb:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes

influxdb-staging:
  enabled: true
  persistence:
    storageClass: rook-ceph-block
    size: 5Ti
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes


kafka-connect-manager:
  influxdbSink:
    # Based on the kafka producers configuration for the BTS
    # https://github.com/lsst-ts/argocd-csc/blob/main/apps/kafka-producers/values-base-teststand.yaml
    connectors:
      auxtel:
        enabled: true
        topicsRegex: "lsst.sal.ATAOS|lsst.sal.ATDome|lsst.sal.ATDomeTrajectory|lsst.sal.ATHexapod|lsst.sal.ATPneumatics|lsst.sal.ATPtg|lsst.sal.ATMCS"
      maintel:
        enabled: true
        topicsRegex: "lsst.sal.MTAOS|lsst.sal.MTDome|lsst.sal.MTDomeTrajectory|lsst.sal.MTPtg"
      mtmount:
        enabled: true
        topicsRegex: "lsst.sal.MTMount"
      comcam:
        enabled: true
        topicsRegex: "lsst.sal.CCCamera|lsst.sal.CCHeaderService|lsst.sal.CCOODS"
      eas:
        enabled: true
        topicsRegex: "lsst.sal.DIMM|lsst.sal.DSM|lsst.sal.ESS|lsst.sal.WeatherForecast"
      latiss:
        enabled: true
        topicsRegex: "lsst.sal.ATCamera|lsst.sal.ATHeaderService|lsst.sal.ATOODS|lsst.sal.ATSpectrograph"
      m1m3:
        enabled: true
        topicsRegex: "lsst.sal.MTM1M3"
      m2:
        enabled: true
        topicsRegex: "lsst.sal.MTHexapod|lsst.sal.MTM2|lsst.sal.MTRotator"
      obssys:
        enabled: true
        topicsRegex: "lsst.sal.Scheduler|lsst.sal.Script|lsst.sal.ScriptQueue|lsst.sal.Watcher"
      ocps:
        enabled: true
        topicsRegex: "lsst.sal.OCPS"
      test:
        enabled: true
        topicsRegex: "lsst.sal.Test"
      pmd:
        enabled: true
        topicsRegex: "lsst.sal.PMD"
      calsys:
        enabled: true
        topicsRegex: "lsst.sal.ATMonochromator|lsst.sal.ATWhiteLight|lsst.sal.CBP|lsst.sal.Electrometer|lsst.sal.FiberSpectrograph|lsst.sal.LinearStage|lsst.sal.TunableLaser"
      mtaircompressor:
        enabled: true
        topicsRegex: "lsst.sal.MTAirCompressor"
      authorize:
        enabled: true
        topicsRegex: "lsst.sal.Authorize"
      lasertracker:
        enabled: true
        topicsRegex: "lsst.sal.LaserTracker"
      genericcamera:
        enabled: true
        topicsRegex: "lsst.sal.GCHeaderService|lsst.sal.GenericCamera"

source-kafka-connect-manager:
  enabled: true
  influxdbSink:
    connectInfluxUrl: "http://sasquatch-influxdb-staging.sasquatch:8086"
    connectInfluxDb: "test"
    connectors:
      source-test:
        enabled: true
        topicsRegex: "source.lsst.sal.Test"

kafdrop:
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes

rest-proxy:
  enabled: true
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes
  kafka:
    topics:
      - test.next-visit
    topicPrefixes:
      - test
      - lsst.dm

chronograf:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://base-lsp.lsst.codes/auth/openid/login
    GENERIC_TOKEN_URL: https://base-lsp.lsst.codes/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://base-lsp.lsst.codes/.well-known/jwks.json
    GENERIC_API_URL: https://base-lsp.lsst.codes/auth/openid/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://base-lsp.lsst.codes
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/base.json

kapacitor:
  persistence:
    storageClass: rook-ceph-block
