strimzi-kafka:
  mirrormaker2:
    enabled: false
    source:
      bootstrapServer: sasquatch-summit-kafka-bootstrap.lsst.codes:9094
      topicsPattern: "lsst.sal.*, registry-schemas"
    replication:
      policy:
        separator: "."
        class: "org.apache.kafka.connect.mirror.DefaultReplicationPolicy"
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
  kafka:
    storage:
      storageClassName: rook-ceph-block
      size: 1Ti
    listeners:
      plain:
        enabled: true
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: "139.229.153.65"
        host: sasquatch-base-kafka-bootstrap.lsst.codes
      brokers:
        - loadBalancerIP: "139.229.153.66"
          host: sasquatch-base-kafka-0.lsst.codes
        - loadBalancerIP: "139.229.153.67"
          host: sasquatch-base-kafka-1.lsst.codes
        - loadBalancerIP: "139.229.153.68"
          host: sasquatch-base-kafka-2.lsst.codes
  kraft:
    enabled: true
  kafkaController:
    enabled: true
    resources:
      requests:
        memory: 8Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "2"
  users:
    replicator:
      enabled: true
    tsSalKafka:
      enabled: true
    kafdrop:
      enabled: true
    telegraf:
      enabled: true
    kafkaConnectManager:
      enabled: true
    consdb:
      enabled: true

influxdb:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes

kafka-connect-manager:
  influxdbSink:
    # Based on the kafka producers configuration for the BTS
    # https://github.com/lsst-ts/argocd-csc/blob/main/apps/kafka-producers/values-base-teststand.yaml
    connectors:
      auxtel:
        enabled: true
        topicsRegex: "lsst.sal.ATAOS|lsst.sal.ATDome|lsst.sal.ATDomeTrajectory|lsst.sal.ATHexapod|lsst.sal.ATPneumatics|lsst.sal.ATPtg|lsst.sal.ATMCS"
      maintel:
        enabled: true
        topicsRegex: "lsst.sal.MTAOS|lsst.sal.MTDome|lsst.sal.MTDomeTrajectory|lsst.sal.MTPtg"
      mtmount:
        enabled: true
        topicsRegex: "lsst.sal.MTMount"
        tasksMax: "8"
      comcam:
        enabled: true
        topicsRegex: "lsst.sal.CCCamera|lsst.sal.CCHeaderService|lsst.sal.CCOODS"
      eas:
        enabled: true
        topicsRegex: "lsst.sal.DIMM|lsst.sal.DSM|lsst.sal.ESS|lsst.sal.HVAC|lsst.sal.WeatherForecast"
      latiss:
        enabled: true
        topicsRegex: "lsst.sal.ATCamera|lsst.sal.ATHeaderService|lsst.sal.ATOODS|lsst.sal.ATSpectrograph"
      m1m3:
        enabled: true
        topicsRegex: "lsst.sal.MTM1M3"
        tasksMax: "8"
      m2:
        enabled: true
        topicsRegex: "lsst.sal.MTHexapod|lsst.sal.MTM2|lsst.sal.MTRotator"
      obssys:
        enabled: true
        topicsRegex: "lsst.sal.Scheduler|lsst.sal.Script|lsst.sal.ScriptQueue|lsst.sal.Watcher"
      ocps:
        enabled: true
        topicsRegex: "lsst.sal.OCPS"
      test:
        enabled: true
        topicsRegex: "lsst.sal.Test"
      pmd:
        enabled: true
        topicsRegex: "lsst.sal.PMD"
      calsys:
        enabled: true
        topicsRegex: "lsst.sal.ATMonochromator|lsst.sal.ATWhiteLight|lsst.sal.CBP|lsst.sal.Electrometer|lsst.sal.FiberSpectrograph|lsst.sal.LinearStage|lsst.sal.TunableLaser"
      mtaircompressor:
        enabled: true
        topicsRegex: "lsst.sal.MTAirCompressor"
      authorize:
        enabled: true
        topicsRegex: "lsst.sal.Authorize"
      lasertracker:
        enabled: true
        topicsRegex: "lsst.sal.LaserTracker"
      genericcamera:
        enabled: true
        topicsRegex: "lsst.sal.GCHeaderService|lsst.sal.GenericCamera"
      lsstcam:
        enabled: true
        topicsRegex: "lsst.sal.MTCamera|lsst.sal.MTHeaderService|lsst.sal.MTOODS"

telegraf-kafka-consumer:
  enabled: false
  kafkaConsumers:
    auxtel:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.ATAOS", "lsst.sal.ATDome", "lsst.sal.ATDomeTrajectory", "lsst.sal.ATHexapod", "lsst.sal.ATPneumatics", "lsst.sal.ATPtg", "lsst.sal.ATMCS" ]
    maintel:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTAOS", "lsst.sal.MTDome", "lsst.sal.MTDomeTrajectory", "lsst.sal.MTPtg" ]
    mtmount:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTMount" ]
    comcam:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.CCCamera", "lsst.sal.CCHeaderService", "lsst.sal.CCOODS" ]
    eas:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.DIMM", "lsst.sal.DSM", "lsst.sal.ESS", "lsst.sal.HVAC", "lsst.sal.WeatherForecast" ]
    latiss:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.ATCamera", "lsst.sal.ATHeaderService", "lsst.sal.ATOODS", "lsst.sal.ATSpectrograph" ]
    m1m3:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTM1M3" ]
    m2:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTHexapod", "lsst.sal.MTM2", "lsst.sal.MTRotator" ]
    obssys:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.Scheduler", "lsst.sal.Script", "lsst.sal.ScriptQueue", "lsst.sal.Watcher" ]
    ocps:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.OCPS" ]
    test:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.Test" ]
    pmd:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.PMD" ]
    calsys:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.ATMonochromator", "lsst.sal.ATWhiteLight", "lsst.sal.CBP", "lsst.sal.Electrometer", "lsst.sal.FiberSpectrograph", "lsst.sal.LinearStage", "lsst.sal.TunableLaser" ]
    mtaircompressor:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTAirCompressor" ]
    authorize:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.Authorize" ]
    lasertracker:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.LaserTracker" ]
    genericcamera:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.GCHeaderService", "lsst.sal.GenericCamera" ]
    lsstcam:
      enabled: true
      replicaCount: 1
      interval: "1s"
      flush_interval: "1s"
      union_mode: "nullable"
      timestamp_format: "unix"
      timestamp_field: "private_efdStamp"
      topicRegexps: |
        [ "lsst.sal.MTCamera", "lsst.sal.MTHeaderService", "lsst.sal.MTOODS" ]

kafdrop:
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes

rest-proxy:
  enabled: true
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes
  kafka:
    topics:
      - test.next-visit
    topicPrefixes:
      - test
      - lsst.dm

chronograf:
  persistence:
    storageClass: rook-ceph-block
  ingress:
    enabled: true
    hostname: base-lsp.lsst.codes
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://base-lsp.lsst.codes/auth/openid/login
    GENERIC_TOKEN_URL: https://base-lsp.lsst.codes/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://base-lsp.lsst.codes/.well-known/jwks.json
    GENERIC_API_URL: https://base-lsp.lsst.codes/auth/openid/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://base-lsp.lsst.codes
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/base.json

kapacitor:
  persistence:
    storageClass: rook-ceph-block
