strimzi-kafka:
  kafka:
    externalListener:
      tls:
        enabled: true
      bootstrap:
        loadBalancerIP: "34.72.64.180"
        host: sasquatch-dev-kafka-bootstrap.lsst.cloud
      brokers:
        - loadBalancerIP: "34.66.20.239"
          host: sasquatch-dev-kafka-0.lsst.cloud
        - loadBalancerIP: "35.192.19.206"
          host: sasquatch-dev-kafka-1.lsst.cloud
        - loadBalancerIP: "34.71.207.19"
          host: sasquatch-dev-kafka-2.lsst.cloud
  users:
    replicator:
      enabled: true
    kafdrop:
      enabled: true
    telegraf:
      enabled: true
    kafkaConnectManager:
      enabled: true

  registry:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      hostname: data-dev.lsst.cloud
      path: /schema-registry(/|$)(.*)
  connect:
    enabled: true
    image: ghcr.io/lsst-sqre/strimzi-jdbc-connector:latest
    jdbc:
      url: https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/10.7.4/kafka-connect-jdbc-10.7.4.jar
      sha512sum: e424c09030c29db90f2403f1a004f649bef062500f00cdb00a4904ca6f3ec52349c6983efd18bb4cd92bff8b6766dd50a7b347df7fd7741aa9db0c69c708a727
    connectors:
      - name: sink-exposure-flexible-metadata
        config:
          topics: lsst.consdb.exposure_flexible_metadata
          table_name_format: consdb.exposure_flexible_metadata
          pk_fields: exposure

influxdb:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud
  resources:
    requests:
      memory: 16Gi
      cpu: 2
    limits:
      memory: 16Gi
      cpu: 2

telegraf-kafka-consumer:
  enabled: true
  kafkaConsumers:
    test:
      enabled: true
      replicaCount: 1
      topicRegexps: |
        [ "lsst.Test.*" ]
    atmcs:
      enabled: false
      replicaCount: 1
      topicRegexps: |
        [ ".*ATMCS" ]

kafdrop:
  cmdArgs: "--message.format=AVRO --topic.deleteEnabled=true --topic.createEnabled=true"
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud

rest-proxy:
  enabled: true
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud
  kafka:
    topics:
      - test.next-visit
    topicPrefixes:
      - test
      - lsst.dm
      - lsst.Test

chronograf:
  ingress:
    enabled: true
    hostname: data-dev.lsst.cloud
  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://data-dev.lsst.cloud/auth/openid/login
    GENERIC_TOKEN_URL: https://data-dev.lsst.cloud/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://data-dev.lsst.cloud/.well-known/jwks.json
    GENERIC_API_URL: https://data-dev.lsst.cloud/auth/openid/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://data-dev.lsst.cloud/
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/idfdev.json
