strimzi-kafka:
  mirrormaker2:
    enabled: true
    source:
      bootstrapServer: sasquatch-summit-kafka-bootstrap.lsst.codes:9094
      topicsPattern: "registry-schemas, lsst.sal.*, lsst.dm.*"
    resources:
      requests:
        cpu: 2
        memory: 4Gi
      limits:
        cpu: 4
        memory: 8Gi
  users:
    replicator:
      enabled: true

influxdb:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  persistence:
    enabled: true
    size: 15Ti
  config:
    coordinator:
      query-timeout: "300s"

source-influxdb:
  enabled: true
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  persistence:
    enabled: true
    size: 15Ti
  config:
    coordinator:
      query-timeout: "300s"

influxdb-enterprise:
  enabled: true
  meta:
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/address-pool: sdf-services
    persistence:
      # -- Enable InfluxDB Enterprise meta pod persistence
      enabled: true
      accessMode: ReadWriteOnce
      size: 16Gi
    # -- InfluxDB Enterprise meta pod resources
    resources:
      requests:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 4Gi
        cpu: 4
  data:
    replicas: 2
    # -- Enable InfluxDB Enterprise data pod persistence
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      storageClass: zfs--rubin-efd
      size: 30Ti
    # -- InfluxDB Enterprise data pod resources
    resources:
      requests:
        memory: 192Gi
        cpu: 8
      limits:
        memory: 192Gi
        cpu: 8

kafka-connect-manager:
  influxdbSink:
    # Based on the kafka producers configuration for the Summit
    # https://github.com/lsst-ts/argocd-csc/blob/main/apps/kafka-producers/values-summit.yaml
    connectors:
      auxtel:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*ATAOS|.*ATDome|.*ATDomeTrajectory|.*ATHexapod|.*ATPneumatics|.*ATPtg|.*ATMCS"
      maintel:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTAOS|.*MTDome|.*MTDomeTrajectory|.*MTPtg"
      mtmount:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTMount"
        tasksMax: "8"
      comcam:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*CCCamera|.*CCHeaderService|.*CCOODS"
      eas:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*DIMM|.*DSM|.*ESS|.*HVAC|.*WeatherForecast"
      latiss:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*ATCamera|.*ATHeaderService|.*ATOODS|.*ATSpectrograph"
      m1m3:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTM1M3"
        tasksMax: "8"
      m2:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTHexapod|.*MTM2|.*MTRotator"
      obssys:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*Scheduler|.*Script|.*ScriptQueue|.*Watcher"
      ocps:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*OCPS"
      test:
        enabled: true
        repairerConnector: false
        topicsRegex: "lsst.sal.Test"
      pmd:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*PMD"
      calsys:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*ATMonochromator|.*ATWhiteLight|.*CBP|.*Electrometer|.*FiberSpectrograph|.*LinearStage|.*TunableLaser"
      mtaircompressor:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTAirCompressor"
      genericcamera:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*GCHeaderService|.*GenericCamera"
      gis:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*GIS"
      mtvms:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*MTVMS"
      lasertracker:
        enabled: true
        repairerConnector: false
        topicsRegex: ".*LaserTracker"

kafdrop:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu

chronograf:
  ingress:
    enabled: true
    hostname: usdf-rsp.slac.stanford.edu

  env:
    GENERIC_NAME: "OIDC"
    GENERIC_AUTH_URL: https://usdf-rsp.slac.stanford.edu/auth/openid/login
    GENERIC_TOKEN_URL: https://usdf-rsp.slac.stanford.edu/auth/openid/token
    USE_ID_TOKEN: 1
    JWKS_URL: https://usdf-rsp.slac.stanford.edu/.well-known/jwks.json
    GENERIC_API_URL: https://usdf-rsp.slac.stanford.edu/auth/userinfo
    GENERIC_SCOPES: openid
    GENERIC_API_KEY: sub
    PUBLIC_URL: https://usdf-rsp.slac.stanford.edu/
    STATUS_FEED_URL: https://raw.githubusercontent.com/lsst-sqre/rsp_broadcast/main/jsonfeeds/usdfprod.json
