apiVersion: v1
kind: ConfigMap
metadata:
  name: "sasquatch-backpack"
  labels:
    {{- include "sasquatch-backpack.labels" . | nindent 4 }}
data:
  SASQUATCH_BACKPACK_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  SASQUATCH_BACKPACK_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  SASQUATCH_BACKPACK_PROFILE: {{ .Values.config.logProfile | quote }}
