apiVersion: v1
kind: Service
metadata:
  name: "sasquatch-backpack"
  labels:
    {{- include "sasquatch-backpack.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "sasquatch-backpack.selectorLabels" . | nindent 4 }}
