apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: "fastapi-bootcamp-jp"
  labels:
    {{- include "fastapi-bootcamp-jp.labels" . | nindent 4 }}
config:
  baseUrl: {{ .Values.global.baseUrl | quote }}
  scopes:
    all:
      - "read:image"
template:
  metadata:
    name: "fastapi-bootcamp-jp"
    {{- with .Values.ingress.annotations }}
    annotations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  spec:
    rules:
      - host: {{ required "global.host must be set" .Values.global.host | quote }}
        http:
          paths:
            - path: {{ .Values.config.pathPrefix | quote }}
              pathType: "Prefix"
              backend:
                service:
                  name: "fastapi-bootcamp-jp"
                  port:
                    number: 8080
