apiVersion: v1
kind: Service
metadata:
  name: "fastapi-bootcamp-jp"
  labels:
    {{- include "fastapi-bootcamp-jp.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "fastapi-bootcamp-jp.selectorLabels" . | nindent 4 }}
