apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gafaelfawrservicetokens.gafaelfawr.lsst.io
  labels:
    app.kubernetes.io/name: gafaelfawr.lsst.io
    app.kubernetes.io/part-of: gafaelfawr
  annotations:
    helm.sh/hook: crd-install
spec:
  group: gafaelfawr.lsst.io
  scope: Namespaced
  names:
    plural: gafaelfawrservicetokens
    singular: gafaelfawrservicetoken
    kind: GafaelfawrServiceToken
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - description: "Service for which to create a token"
          jsonPath: ".spec.service"
          name: "Service"
          type: string
        - description: "If the secret was created/updated successfully"
          jsonPath: >-
            .status.conditions[?(@.type=="SecretCreated")].status
          name: "Succeeded"
          type: string
        - description: "Reason for the current status"
          jsonPath: >-
            .status.conditions[?(@.type=="SecretCreated")].reason
          name: "Reason"
          type: string
        - description: "More information about the current status"
          jsonPath: >-
            .status.conditions[?(@.type=="SecretCreated")].message
          name: "Message"
          type: string
        - description: "Time when the condition was last updated"
          jsonPath: >-
            .status.conditions[?(@.type=="SecretCreated")].lastTransitionTime
          name: "Last Transition"
          type: date
        - description: "Time when the GafaelfawrServiceToken was created"
          jsonPath: .metadata.creationTimestamp
          name: Age
          type: date
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          description: >-
            GafaelfawrServiceTokenSpec defines the desired state of the
            GafaelfawrServiceToken.
          type: object
          properties:
            spec:
              type: object
              description: "Specification of the token secret to create."
              properties:
                service:
                  type: string
                  description: "Username field of the service token."
                scopes:
                  type: array
                  description: >-
                    Array of scopes that should be granted to the service
                    token.
                  items:
                    type: string
                    pattern: "^[a-zA-Z0-9:._-]+$"
            status:
              type: object
              description: >-
                GafaelfawrServiceTokenStatus defines the observed state of the
                GafaelfawrServiceToken.
              x-kubernetes-preserve-unknown-fields: true
