apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obsloctap.fullname" . }}
  labels:
    {{- include "obsloctap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "obsloctap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "obsloctap.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: "pull-secret"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
        # butler-secrets-raw is the secrets we get from vault
        - name: "butler-secrets-raw"
          secret:
            secretName: {{ include "obsloctap.fullname" . }}
        # butler-secrets are the copied and chmoded versions
        - name: "butler-secrets"
          emptyDir: {}
        - name: "cache-dir"
          emptyDir: {}
        - name: "tmp"
          emptyDir: {}
      # Have to fix permissions on the pgpass file.
      # init container pattern borrowed from vo-cutouts.
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "all"
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: "butler-secrets"
              mountPath: "/home/worker/.lsst/"
            - name: "butler-secrets-raw"
              mountPath: "/home/worker/secrets-raw/"
              readOnly: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /obsloctap
              port: http
          resources:
              mountPath: "/tmp"
          volumeMounts:
            - name: butler-secrets
              mountPath: "/home/worker/.lsst/"
          env:
            - name: "PGPASS"
              valueFrom:
                secretKeyRef:
                  name: obsloctap-postgres
                  key: "password"
{{- range $key, $value := .Values.environment }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
