apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: obsloctap-postgress
  labels:
    {{- include "obsloctap.labels" . | nindent 4 }}
spec:
  path: "secret/rubin/usdf-butler/postgres"
  type: Opaque
