---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: squarebot
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.app_mention"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.message.channels"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.message.groups"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.message.im"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.message.mpim"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
      - resource:
          type: topic
          name: "rubin.square.events.squarebot.slack.interaction"
          patternType: literal
        type: allow
        host: "*"
        operations:
          - "Write"
          - "Describe"
