# Default values for latiss prompt-proto-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Annotations for the prompt-proto-service pod
podAnnotations:
  autoscaling.knative.dev/min-scale: "3"
  autoscaling.knative.dev/max-scale: "100"
  autoscaling.knative.dev/target-utilization-percentage: "80"
  # Update this field if `make apply` by itself doesn't make a new revision.
  revision: "32"

knative:
  ephemeralStorageRequest: "8Gi"
  ephemeralStorageLimit: "20Gi"
  timeout: 900

image:
  repository: ghcr.io/lsst-dm/prompt-proto-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: AuxTel20230524-w_2023_20

instrument:
  name: LATISS
  pipelines: ""
  skymap: latiss_v1
  calibRepo: /app/butler

s3:
  imageBucket: rubin-pp
  endpointUrl: https://s3dfrgw.slac.stanford.edu
  auth_env: true

imageNotifications:
  kafkaClusterAddress: prompt-processing-kafka-bootstrap.kafka:9092
  topic: rubin-prompt-processing
  imageTimeout: 120

apdb:
  ip: usdf-prompt-processing-dev.slac.stanford.edu:5432
  db: lsst-devl
  user: rubin
  namespace: pp_apdb

registry:
  ip: usdf-butler.slac.stanford.edu:5432
  db: lsstdb1
  user: rubin



namespace: prompt-proto-service-latiss

vaultSecretsPath: "secret/rubin/usdf-alert-stream-broker-dev/prompt-processing-dev/prompt-proto-service-latiss"