# Default values for prompt-proto-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Override the base name for resources
nameOverride: ""

# -- Override the full name for resources (includes the release name)
fullnameOverride: "prompt-proto-service"

# -- Annotations for the prompt processing service
podAnnotations:
  class: kpa.autoscaling.knative.dev

# -- Knative settings
knative:
  ephemeralStorageRequest: "8Gi"
  ephemeralStorageLimit: "20Gi"
  timeout: 900

containerConcurrency: 1

namespace: prompt-proto-service

imageNotifications:
  imageTimeout: '120'

image:
  repository: ghcr.io/lsst-dm/prompt-proto-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

s3:
  disableBucketValidation: '0'

additionalVolumeMounts: []

imagePullSecrets: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100

nodeSelector: {}

tolerations: []

affinity: {}
