controller:
  config:
    safir:
      logLevel: "DEBUG"
    fileserver:
      enabled: false
      timeout: 43200
    images:
      source:
        type: "docker"
        registry: "registry.hub.docker.com"
        repository: "lsstsqre/sciplat-lab"
      recommendedTag: "recommended"
      numReleases: 1
      numWeeklies: 2
      numDailies: 3
    lab:
      homedirSchema: "username"
      homedirPrefix: "/sps/lsst/users"
      homedirSuffix: "rsp_home"
      env:
        AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod,https://github.com/rubin-dp0/tutorial-notebooks@prod"
        NO_ACTIVITY_TIMEOUT: "432000"
        CULL_KERNEL_IDLE_TIMEOUT: "432000"
        CULL_TERMINAL_INACTIVE_TIMEOUT: "432000"
      sizes:
        small:
          cpu: 1.0
          memory: 4Gi
        medium:
          cpu: 2.0
          memory: 16Gi
        large:
          cpu: 8.0
          memory: 32Gi
      initContainers:
        - name: "homecreation"
          image: "registry.hub.docker.com/gabrimaine/initdir:0.0.1_beta"
          privileged: true
          volumes:
            - containerPath: "/pbs/home"
              source:
                type: "hostPath"
                path: "/pbs/home"
            - containerPath: "/pbs/throng"
              source:
                type: "hostPath"
                path: "/pbs/throng"
            - containerPath: "/sps"
              source:
                type: "hostPath"
                path: "/sps"
      volumes:
        - containerPath: "/pbs/home"
          source:
            type: "hostPath"
            path: "/pbs/home"
        - containerPath: "/pbs/throng"
          source:
            type: "hostPath"
            path: "/pbs/throng"
        - containerPath: "/sps"
          source:
            type: "hostPath"
            path: "/sps"
jupyterhub:
  hub:
    baseUrl: "/n3"
    config:
      ServerApp:
        shutdown_no_activity_timeout: 432000
    db:
      url: "postgresql://nublado3@postgres.postgres/nublado3"

  cull:
    enabled: true
    users: false
    removeNamedServers: false
    timeout: 432000
    every: 300
    maxAge: 2160000
