controller:
  config:
    images:
      source:
        type: "docker"
        registry: "registry.hub.docker.com"
        repository: "lsstsqre/sciplat-lab"
    lab:
      env:
        AUTO_REPO_SPECS: "https://github.com/lsst-sqre/system-test@prod,https://github.com/rubin-dp0/tutorial-notebooks@prod"
        FIREFLY_HTML: "slate.html"
        CULL_TERMINAL_INACTIVE_TIMEOUT: "432000"  # 5 days
      initContainers:
        - name: "inithome"
          image:
            repository: "ghcr.io/lsst-sqre/nublado-inithome"
            tag: "6.1.0"
          privileged: true
          volumeMounts:
            - containerPath: "/home"
              volumeName: "home"
      sizes:
        - size: small
          cpu: 1.0
          memory: 2Gi
        - size: medium
          cpu: 2.0
          memory: 4Gi
        - size: large
          cpu: 4.0
          memory: 8Gi
      volumes:
        - name: "home"
          source:
            serverPath: "/data/home"
            server: ""
            type: "nfs"
        - name: "project"
          source:
            serverPath: "/data/project"
            server: ""
            type: "nfs"
        - name: "scratch"
          source:
            serverPath: "/data/scratch"
            server: ""
            type: "nfs"
      volumeMounts:
        - containerPath: "/home"
          volumeName: "home"
        - containerPath: "/project"
          volumeName: "project"
        - containerPath: "/scratch"
          volumeName: "scratch"

jupyterhub:
  hub:
    baseUrl: "/nb"
    db:
      url: "postgresql://jhubsessions@129.114.35.51/jhubsessions01"
      upgrade: true
  cull:
    timeout: 432000  # 5 days
    maxAge: 691200  # 8 days

hub:
  internalDatabase: false
