controller:
  image:
    tag: "tickets-DM-38279-queue"
    pullPolicy: "Always"
  config:
    images:
      source:
        type: "google"
        location: "us-central1"
        projectId: "rubin-shared-services-71ec"
        repository: "sciplat"
        image: "sciplat-lab"
      recommendedTag: "recommended"
      numReleases: 1
      numWeeklies: 2
      numDailies: 3
    lab:
      initContainers:
        - name: "initdir"
          image: "ghcr.io/lsst-sqre/initdir:0.0.3"
          privileged: true
          volumes:
            - containerPath: "/home"
              serverPath: "/share1/home"
              server: "10.87.86.26"
              mode: "rw"
      volumes:
        - containerPath: "/home"
          serverPath: "/share1/home"
          server: "10.87.86.26"
          mode: "rw"
        - containerPath: "/project"
          serverPath: "/share1/project"
          server: "10.87.86.26"
          mode: "rw"
        - containerPath: "/scratch"
          serverPath: "/share1/scratch"
          server: "10.87.86.26"
          mode: "rw"
jupyterhub:
  hub:
    image:
      tag: "tickets-DM-38279-queue"
      pullPolicy: "Always"
