{{- if (index .Values "applications" "bootcamp-hfc") -}}
apiVersion: v1
kind: Namespace
metadata:
  name: "bootcamp-hfc"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "bootcamp-hfc"
  namespace: "argocd"
  finalizers:
    - "resources-finalizer.argocd.argoproj.io"
spec:
  destination:
    namespace: "bootcamp-hfc"
    server: "https://kubernetes.default.svc"
  project: "rubin"
  source:
    path: "applications/bootcamp-hfc"
    repoURL: {{ .Values.repoUrl | quote }}
    targetRevision: {{ .Values.targetRevision | quote }}
    helm:
      parameters:
        - name: "global.host"
          value: {{ .Values.fqdn | quote }}
        - name: "global.baseUrl"
          value: "https://{{ .Values.fqdn }}"
        - name: "global.vaultSecretsPath"
          value: {{ .Values.vaultPathPrefix | quote }}
      valueFiles:
        - "values.yaml"
        - "values-{{ .Values.name }}.yaml"
{{- end -}}