image:
  pullPolicy: Always

config:
  logLevel: "DEBUG"
  worker:
    workerCount: 1
    identities:
      - username: "bot-noteburst01"
      - username: "bot-noteburst02"
    enableLivenessCheck: false # always fails at USDF

# Use SSD for Redis storage.
redis:
  persistence:
    storageClass: "wekafs--sdf-k8s01"
