image:
  tag: "tickets-DM-43454"
  pullPolicy: Always

config:
  logLevel: "DEBUG"
  worker:
    workerCount: 1
    identities:
      - username: "bot-noteburst90000"
        uid: 90000
        gid: 90000
      - username: "bot-noteburst90001"
        uid: 90001
        gid: 90001
      - username: "bot-noteburst90002"
        uid: 90002
        gid: 90002
      - username: "bot-noteburst90003"
        uid: 90003
        gid: 90003
      - username: "bot-noteburst90004"
        uid: 90004
        gid: 90004
      - username: "bot-noteburst90005"
        uid: 90005
        gid: 90005

# Use SSD for Redis storage.
redis:
  persistence:
    storageClass: "premium-rwo"
