image:
  pullPolicy: Always

config:
  logLevel: "DEBUG"
  worker:
    workerCount: 1
    identities:
      - username: "bot-noteburst-01"
      - username: "bot-noteburst-02"

# Use SSD for Redis storage.
redis:
  persistence:
    storageClass: "wekafs--sdf-k8s01"
