replicaCount: 4

image:
  tag: "suit-2023.1.0"

config:
  volumes:
    workareaNfs:
      path: "/share1/home/firefly/shared-workarea"
      server: "10.22.240.130"

resources:
  limits:
    memory: "30Gi"
