replicaCount: 4

config:
  volumes:
    workareaNfs:
      path: "/share1/home/firefly/shared-workarea"
      server: "10.22.240.130"
  ssotap: "ssotap"

image:
  tag: "portal-2024.1.3"


resources:
  limits:
    memory: "30Gi"
