namespace: &ns uws

csc_collector:
  namespace: *ns

  secrets:
  - name: nexus3-docker
    key: pull-secret
    type: kubernetes.io/dockerconfigjson
  - name: ts-salkafka
    key: ts/software/ts-salkafka

atocps:
  enabled: true
  namespace: *ns
  classifier: ocps1
  image:
    repository: ts-dockerhub.lsst.org/dmocps
    pullPolicy: Always
  env:
    RUN_ARG: 1

ccocps:
  enabled: true
  namespace: *ns
  classifier: ocps2
  image:
    repository: ts-dockerhub.lsst.org/dmocps
    pullPolicy: Always
  env:
    RUN_ARG: 2
