apiVersion: v2
name: uws
version: 1.0.0
description: Deployment for the UWS and DM OCPS CSCs
dependencies:
- name: csc_collector
  version: 1.0.0
- name: csc
  alias: atocps
  version: 1.0.0
- name: csc
  alias: ccocps
  version: 1.0.0
- name: uws-api-server
  version: 1.5.0
