apiVersion: v2
name: telegraf-ds
version: 1.0.0
description: SQuaRE DaemonSet (K8s) telemetry collection service
dependencies:
  - name: telegraf-ds
    version: 1.1.4
    repository: https://helm.influxdata.com/
annotations:
  phalanx.lsst.io/docs: |
    - id: "SQR-061"
      title: "Monitoring architecture for the RSP"
      url: "https://sqr-061.lsst.io/"
