imagePullSecrets:
- name: pull-secret

frontend:
  debug: true
  env:
  - name: S3_ENDPOINT_URL
    value: "https://s3dfrgw.slac.stanford.edu"
  - name: RAPID_ANALYSIS_LOCATION
    value: "USDF"
  image:
    tag: v2.2.0
    pullPolicy: Always
