rubintv:
  imagePullSecrets:
  - name: pull-secret

  frontend:
    debug: true
    env:
    - name: S3_ENDPOINT_URL
      value: &s3E "https://s3dfrgw.slac.stanford.edu"
    - name: RAPID_ANALYSIS_LOCATION
      value: "USDF"
    image:
      tag: v2.2.0
      pullPolicy: Always

  workers:
    replicas: 1
    image:
      repository: ts-dockerhub.lsst.org/rapid-analysis
      tag: c0036
      pullPolicy: Always
    uid: 73006
    gid: 73006
    scriptsLocation: /repos/rubintv_analysis_service/scripts
    script: rubintv_worker.py -a rubintv -p 8080 -c /repos/rubintv_analysis_service/scripts/config-temporal.yaml
    env:
    - name: S3_ENDPOINT_URL
      value: *s3E
    - name: DAF_BUTLER_REPOSITORY_INDEX
      value: "s3://rubin-summit-users/data-repos.yaml"
    - name: DAF_BUTLER_REPOSITORY
      value: "/sdf/group/rubin/repo/ir2/butler.yaml"
    volumes:
    - name: sdf-group-rubin
      persistentVolumeClaim:
        name: sdf-group-rubin
        storageClassName: sdf-group-rubin
        capacity: 1Gi
      accessMode: ReadOnlyMany
      mountPath: /sdf/group/rubin
    - name: sdf-data-rubin
      persistentVolumeClaim:
        name: sdf-data-rubin
        storageClassName: sdf-data-rubin
        capacity: 1Gi
      accessMode: ReadOnlyMany
      mountPath: /sdf/data/rubin
    resources:
      limits:
        cpu: 2.0
        memory: "8Gi"
