rubintv:
  siteTag: "summit"

  imagePullSecrets:
  - name: pull-secret

  frontend:
    debug: true
    env:
    - name: S3_ENDPOINT_URL
      value: &s3E "https://s3.rubintv.cp.lsst.org"
    - name: RAPID_ANALYSIS_LOCATION
      value: "SUMMIT"
    image:
      tag: v2.2.0
      pullPolicy: Always

  workers:
    replicas: 0
    image:
      repository: ts-dockerhub.lsst.org/rapid-analysis
      tag: c0037
      pullPolicy: Always
    uid: 73006
    gid: 73006
    scriptsLocation: /repos/rubintv_analysis_service/scripts
    script: rubintv_worker.py -a rubintv-dev -p 8080 -l summit
    env:
    - name: S3_ENDPOINT_URL
      value: *s3E
    - name: DAF_BUTLER_REPOSITORY_INDEX
      value: "s3://rubin-summit-users/data-repos.yaml"
    - name: DAF_BUTLER_REPOSITORY
      value: "/sdf/group/rubin/repo/ir2/butler.yaml"
    - name: DEPLOY_BRANCH
      value: "deploy-summit"
    resources:
      limits:
        cpu: 2.0
        memory: "8Gi"

global:
  tsVaultSecretsPath: /ts/software
