siteTag: "usdf-dev"

frontend:
  debug: true
  env:
  - name: http_proxy
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: https_proxy
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: no_proxy
    value: ".sdf.slac.stanford.edu,.slac.stanford.edu,localhost,127.0.0.1"
  image:
    tag: tickets-DM-40149
    pullPolicy: Always

workers:
  replicas: 1
  image:
    repository: lsstts/rubintv-broadcaster
    tag: c0030_usdf
    pullPolicy: Always
  uid: 15517
  gid: 4085
  env:
  - name: http_proxy
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: https_proxy
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: squid_proxy
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: no_proxy
    value: ".sdf.slac.stanford.edu,.slac.stanford.edu,localhost,127.0.0.1"
  - name: HTTP_PROXY
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: HTTPS_PROXY
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: SQUID_PROXY
    value: "http://sdfproxy.sdf.slac.stanford.edu:3128"
  - name: NO_PROXY
    value: ".sdf.slac.stanford.edu,.slac.stanford.edu,localhost,127.0.0.1"
  - name: DEPLOY_BRANCH
    value: "deploy-rubintv-worker"
  - name: S3_ENDPOINT_URL
    value: "https://s3dfrgw.slac.stanford.edu"
  - name: DAF_BUTLER_REPOSITORY_INDEX
    value: "s3://rubin-summit-users/data-repos.yaml"
  - name: DAF_BUTLER_REPOSITORY
    value: "/sdf/group/rubin/repo/ir2/butler.yaml"
  envSecrets:
  - name: ASTROMETRY_NET_API_KEY
    secretName: rubintv-secret
    secretKey: astrometry-net-api-key
  imagePullSecrets:
  - name: pull-secret
  volumes:
  - name: sdf-group-rubin
    persistentVolumeClaim:
      name: sdf-group-rubin
      storageClassName: sdf-group-rubin
      capacity: 1Gi
    accessMode: ReadOnlyMany
    mountPath: /sdf/group/rubin
  - name: sdf-data-rubin
    persistentVolumeClaim:
      name: sdf-data-rubin
      storageClassName: sdf-data-rubin
      capacity: 1Gi
    accessMode: ReadOnlyMany
    mountPath: /sdf/data/rubin
  - name: fs-ddn-sdf-group-lsst
    persistentVolumeClaim:
      name: fs-ddn-sdf-group-lsst
      storageClassName: fs-ddn-sdf-group-lsst
      capacity: 1Gi
    accessMode: ReadOnlyMany
    mountPath: /fs/ddn/sdf/group/lsst
  resources:
    limits:
      cpu: 2.0
      memory: "8Gi"
  # credentialFile: google_write_creds
  # vaultPrefixPath: secret/rubin/usdf-rubintv-broadcaster-cleanroom
  # pullSecretsPath: ts/software/nexus3-docker
  # rubinTvSecretsPath: ts/software/rubintv
  # credentialSecretsPath: rubintv-broadcaster
  # butlerSecret:
  #   key: butler-secret
  #   containerPath: /secrets
  #   dbUser: rubin
