apiVersion: v2
name: control-system-test
version: 1.0.0
description: Deployment for the Test CSCs and Integration Testing Workflows
dependencies:
- name: csc_collector
  version: 1.0.0
- name: csc
  alias: test42
  version: 1.0.0
- name: integration-testing
  version: 1.0.0
  condition: integration-testing.enabled
