apiVersion: v1
kind: Service
metadata:
  name: "jeremym-fastapi-example"
  labels:
    {{- include "jeremym-fastapi-example.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "jeremym-fastapi-example.selectorLabels" . | nindent 4 }}
