cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfint-tap"

  config:
    qserv:
      # host: "qserv-int.slac.stanford.edu:4040"
      host: "qserv-prod.slac.stanford.edu:4040"
      jdbcParams: "?enabledTLSProtocols=TLSv1.2"
