cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-idfint-tap"

  config:
    qserv:
      host: "134.79.23.227:4040"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"

  cloudsql:
    enabled: true
    instanceConnectionName: "science-platform-int-dc5d:us-central1:science-platform-int-8f439af2"
    serviceAccount: "tap-service@science-platform-int-dc5d.iam.gserviceaccount.com"
    database: "tap"
