cadc-tap:
  tapSchema:
    image:
      repository: "gabrimaine/tap-schema-ccin2p3:v0.1"

  config:
    gcsBucket: "lsstrsp:async-results.lsst.codes"
    gcsBucketUrl: "https://ccs3rubin.in2p3.fr:8080"
    gcsBucketType: "S3"

    qserv:
      host: "ccqserv201.in2p3.fr:30040"
