cadc-tap:
  tapSchema:
    image:
      repository: "lsstsqre/tap-schema-usdf-prod-tap"

  config:
    qserv:
      host: "172.24.49.51:4040"
      jdbcParams: "?enabledTLSProtocols=TLSv1.3"
      passwordEnabled: true

    gcsBucket: "rubin:rubin-qserv"
    gcsBucketUrl: "https://s3dfrgw.slac.stanford.edu"
    gcsBucketType: "S3"
