apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: fan-out-producer
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: prompt-processing-kafka-secret
          key: fan-out-producer-password
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: "fanned-out-comcamsim-events"
          patternType: literal
        type: allow
        host: "*"
        operation: All
      - resource:
          type: topic
          name: "fanned-out-hsc-events"
          patternType: literal
        type: allow
        host: "*"
        operation: All
      - resource:
          type: topic
          name: "fanned-out-latiss-events"
          patternType: literal
        type: allow
        host: "*"
        operation: All
      - resource:
          type: topic
          name: "fanned-out-latiss-events-2"
          patternType: literal
        type: allow
        host: "*"
        operation: All
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: fan-out-consumer
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: prompt-processing-kafka-secret
          key: fan-out-consumer-password
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: "fanned-out-comcamsim-events"
          patternType: literal
        type: allow
        host: "*"
        operation: Read
      - resource:
          type: topic
          name: "fanned-out-hsc-events"
          patternType: literal
        type: allow
        host: "*"
        operation: Read
      - resource:
          type: topic
          name: "fanned-out-latiss-events"
          patternType: literal
        type: allow
        host: "*"
        operation: Read
      - resource:
          type: topic
          name: "fanned-out-latiss-events-2"
          patternType: literal
        type: allow
        host: "*"
        operation: Read
{{- if .Values.users.kafdrop.enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafdrop
  labels:
    strimzi.io/cluster: {{ .Values.cluster.name }}
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: prompt-processing-kafka-secret
          key: kafdrop-password
  authorization:
    type: simple
    acls:
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: topic
          name: "*"
          patternType: literal
        type: allow
        host: "*"
        operation: All
{{- end }}
