[project]
title = "Phalanx"
copyright = "2020-2022 Association of Universities for Research in Astronomy, Inc. (AURA)"
base_url = "https://phalanx.lsst.io"
github_url = "https://github.com/lsst-sqre/phalanx"
github_default_branch = "master"
version = "Current"

[sphinx]
rst_epilog_file = "_rst_epilog.rst"
extensions = [
  "sphinx_diagrams"
]

[sphinx.linkcheck]
ignore = [
    '^http://localhost',
    '^http(s)*://ls.st',
]
