{{- if .Values.ingress.enabled -}}
{{- $fullName := include "squareone.fullname" . -}}
apiVersion: gafaelfawr.lsst.io/v1alpha1
kind: GafaelfawrIngress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "squareone.labels" . | nindent 4 }}
config:
  baseUrl: {{ .Values.global.baseUrl | quote }}
  scopes:
    anonymous: true
template:
  metadata:
    name: {{ $fullName }}
    annotations:
      {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  spec:
    rules:
      - host: {{ required "global.host must be set" .Values.global.host | quote }}
        http:
          paths:
            - path: "/"
              pathType: "Prefix"
              backend:
                service:
                  name: {{ $fullName }}
                  port:
                    number: 80
{{- end }}
