apiVersion: v1
kind: ConfigMap
metadata:
  name: "mpc-lookup"
  labels:
    {{- include "mpc-lookup.labels" . | nindent 4 }}
data:
  MPC_LOOKUP_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  MPC_LOOKUP_PATH_PREFIX: {{ .Values.config.pathPrefix | quote }}
  MPC_LOOKUP_PROFILE: {{ .Values.config.logProfile | quote }}
