apiVersion: v1
kind: Service
metadata:
  name: "mpc-lookup"
  labels:
    {{- include "mpc-lookup.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: 8080
      targetPort: "http"
      protocol: "TCP"
      name: "http"
  selector:
    {{- include "mpc-lookup.selectorLabels" . | nindent 4 }}
