obsenv-api:
  image:
    repository: rubin-cr.lsst.org/obsenv-api
    tag: tickets-DM-46822
    pullPolicy: Always
  config:
    logLevel: "DEBUG"
  nfsMount:
    server: nfs-obsenv.tu.lsst.org

obsenv-ui:
  image:
    repository: rubin-cr.lsst.org/obsenv-ui
    tag: tickets-DM-46822
    pullPolicy: Always
  config:
    pathPrefix: /obsenv-management
    authGroup: lsst-ts-obsenv-admin-group
