obsenv-api:
  image:
    repository: mareuter/obsenv-api
    tag: develop
    pullPolicy: Always
  config:
    useFakeObsenvManager: true

obsenv-ui:
  image:
    repository: mareuter/obsenv-ui
    tag: develop
    pullPolicy: Always
  config:
    pathPrefix: /obsenv-management/(.*)
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/use-regex: "true"
