apiVersion: v2
name: live-tap
version: 1.0.0
description: IVOA TAP service
sources:
  - https://github.com/lsst-sqre/tap-postgres
  - https://github.com/opencadc/tap
appVersion: "1.12"

dependencies:
  - name: cadc-tap
    version: 1.0.0
    repository: "file://../../charts/cadc-tap/"
